/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package centerstore.purchasereturn;

import java.awt.Color;
import java.awt.event.ActionListener;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.awt.event.KeyListener;
import java.beans.PropertyChangeListener;
import java.text.NumberFormat;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.ListSelectionModel;
import javax.swing.event.DocumentListener;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import reusableClass.Function;


/**
 *
 * @author SUSHIL
 */
public class PurchaseReturnView extends javax.swing.JDialog {
    private String RItemId = "";
    private String PurchaseId = null;;
    private String RDistributorId = null;;
     private ListSelectionModel selectionModel;

    /**
     * Creates new form PurchaseReturnView
     */
    public PurchaseReturnView(JFrame parent,boolean modal) {
       super(parent,modal);
        initComponents();
       // jPanel1.setVisible(false);
        selectionModel = tblItemList.getSelectionModel();
        selectionModel.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        disableReturnBtn();
        txtBaseUnit.addFocusListener(new SetFocusListener(txtBaseUnit));
        txtDistributor.addFocusListener(new SetFocusListener(txtDistributor));
        txtItemName.addFocusListener(new SetFocusListener(txtItemName));
        txtPurchaseAmount.addFocusListener(new SetFocusListener(txtPurchaseAmount));
        txtPurchaseQuantity.addFocusListener(new SetFocusListener(txtPurchaseQuantity));
        txtReturnAmount.addFocusListener(new SetFocusListener(txtReturnAmount));
        txtReturnQuantity.addFocusListener(new SetFocusListener(txtReturnQuantity));
        txtSearch.addFocusListener(new SetFocusListener(txtSearch));
        txtStockQuantity.addFocusListener(new SetFocusListener(txtStockQuantity));
        //make button ready for enter also
        Function.setButtonForEnter(btnCancel);
        Function.setButtonForEnter(btnReturn);
        Function.setButtonForEnter(btnSearch);
     //   txtareaReturnReason.addFocusListener(new SetFocusListener(txtareaReturnReason));
         /*
         * centering the frame
         */
        setLocationRelativeTo(null);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblItemName = new javax.swing.JLabel();
        txtItemName = new javax.swing.JTextField();
        lblStockQuantity = new javax.swing.JLabel();
        txtStockQuantity = new javax.swing.JTextField();
        lblReturnQuantity = new javax.swing.JLabel();
        txtReturnQuantity = new javax.swing.JTextField();
        lblReturnReason = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtareaReturnReason = new javax.swing.JTextArea();
        lblDistributorName = new javax.swing.JLabel();
        txtDistributor = new javax.swing.JTextField();
        lblItemBaseUnit = new javax.swing.JLabel();
        txtBaseUnit = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtReturnAmount = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPurchaseQuantity = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPurchaseAmount = new javax.swing.JTextField();
        btnReturn = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblItemList = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Purchase Return Window");
        setName("Purchase Return"); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblItemName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblItemName.setText("Item Name:*");

        txtItemName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lblStockQuantity.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblStockQuantity.setText("Stock Quantity:");

        txtStockQuantity.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lblReturnQuantity.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblReturnQuantity.setText("Return Quantity:*");

        txtReturnQuantity.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lblReturnReason.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblReturnReason.setText("Return Reason:");

        txtareaReturnReason.setColumns(20);
        txtareaReturnReason.setRows(5);
        jScrollPane1.setViewportView(txtareaReturnReason);

        lblDistributorName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDistributorName.setText("Distributor Name:");

        txtDistributor.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lblItemBaseUnit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblItemBaseUnit.setText("Item BaseUnit:");

        txtBaseUnit.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Purchase Amount:");

        txtReturnAmount.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtReturnAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReturnAmountActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Purchase Quantity:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Return Amount:*");

        txtPurchaseAmount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPurchaseAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPurchaseAmountActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblReturnReason, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblReturnQuantity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblStockQuantity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDistributorName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblItemName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtReturnQuantity, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                            .addComponent(txtPurchaseQuantity, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDistributor, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblItemBaseUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtStockQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtPurchaseAmount, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtBaseUnit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE))
                    .addComponent(txtReturnAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDistributorName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDistributor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPurchaseQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblItemBaseUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBaseUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStockQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStockQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPurchaseAmount, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblReturnQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtReturnQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtReturnAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblReturnReason, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btnReturn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnReturn.setMnemonic('R');
        btnReturn.setText("Return");

        btnCancel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnCancel.setMnemonic('C');
        btnCancel.setText("Cancel");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Purchase Item"));

        tblItemList.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblItemList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblItemList.setRowHeight(20);
        jScrollPane2.setViewportView(tblItemList);
        tblItemList.getTableHeader().setReorderingAllowed(false);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 255));
        jLabel2.setText("Search for the Item to return");

        txtSearch.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        btnSearch.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnSearch.setMnemonic('S');
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearch)
                .addGap(40, 40, 40))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(btnReturn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancel)
                .addGap(129, 129, 129))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtReturnAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReturnAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReturnAmountActionPerformed

    private void txtPurchaseAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPurchaseAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPurchaseAmountActionPerformed
    public String getPurchaseId(){
        return PurchaseId;
    }
    public void setPurchaseId(String pid){
        PurchaseId = pid;
    }
    public String getRDistributorId(){
    return RDistributorId;
}
public void setRDistributorId(String did){
    RDistributorId = did;
    
}
    public String getRItemId(){
    return RItemId;
}
public void setRItemId(String id){
    RItemId = id;
}
    public String getRItemName(){
    return txtItemName.getText();
}
public void setRItemName(String ItemName){
    txtItemName.setText(ItemName);
    
}
public void setPurchaseAmount(String amt){
    txtPurchaseAmount.setText(amt);
}
public String getPurchaseAmount(){
     return txtPurchaseAmount.getText();
}
public String getRDistributorName(){
    return txtDistributor.getText();
}
public void setRDistributorName(String DName){
    txtDistributor.setText(DName);
}
public void setPurchaseQuantity(String qty){
    txtPurchaseQuantity.setText(qty);
}
public String getPurchaseQuantity(){
     return txtPurchaseQuantity.getText();
}
public void setStockQuantity(String StockQuantity){
    txtStockQuantity.setText(StockQuantity);
} 
public String getStockQuantity(){
    return txtStockQuantity.getText();
}
public String getReturnQuantity(){
    return  txtReturnQuantity.getText();
}
public void setReturnQuantity(String ReturnQuantity){
    txtReturnQuantity.setText(ReturnQuantity);
}
public String getReturnReason(){
    return txtareaReturnReason.getText();
}
public void setReturnReason(String RReason){
    txtareaReturnReason.setText(RReason);
}
public String getBaseUnit(){
    return txtBaseUnit.getText();
}
public void setBaseUnit(String BaseUnit){
    txtBaseUnit.setText(BaseUnit);
}
public String getReturnAmount(){
    return txtReturnAmount.getText();
}
public void setReturnAmount(String amount){
    txtReturnAmount.setText(amount);
}
public void disableReturnBtn(){
    btnReturn.setEnabled(false);
}
public void enableReturnBtn(){
    btnReturn.setEnabled(true);
}

    public JButton getBtnSearch() {
        return btnSearch;
    }

public void setPurchaseReturn(String[] PurchaseData){
    try{
   // RItemId =PurchaseData[0];
    PurchaseId = PurchaseData[0];
        txtItemName.setText(PurchaseData[1]);
   
    txtPurchaseQuantity.setText(PurchaseData[2]);
  //  txtReturnQuantity.setText(PurchaseData[4]);
    txtBaseUnit.setText(PurchaseData[3]);
  //  RDistributorId =  PurchaseData[4];
     txtDistributor.setText(PurchaseData[4]);
  //  txtareaReturnReason.setText(PurchaseData[6]);
     NumberFormat decimal = NumberFormat.getNumberInstance();
     txtPurchaseAmount.setText(decimal.parse(PurchaseData[5]).toString());
    }
    catch(Exception e){
        JOptionPane.showMessageDialog(null, e+"from set purchasereturn");
    }
    
    
}
public String[] getPurchaseReturn(){
    String[] PurchaseReturnData = new String[11];
    try{
    PurchaseReturnData[0] =getRItemId();
    PurchaseReturnData[1] = getRItemName();
    
   // PurchaseReturnData[2] = getRDistributorName();
    PurchaseReturnData[2] = getStockQuantity();
    PurchaseReturnData[3] = getReturnQuantity();
    PurchaseReturnData[4] = getBaseUnit();
    PurchaseReturnData[5] = getReturnReason();
    PurchaseReturnData[6] = getRDistributorId();
    PurchaseReturnData[7] = getReturnAmount();
    PurchaseReturnData[8] = getPurchaseId();
    PurchaseReturnData[9] = getPurchaseQuantity();
    PurchaseReturnData[10] = getPurchaseAmount();
    }
    catch(Exception e){
        JOptionPane.showMessageDialog(null, e+"from getPuchasereturn");
    }
    return PurchaseReturnData;
    
}
public void clearall(){
    setRItemId("");
    setRItemName("");
    setRDistributorName("");
    setStockQuantity("");
    setReturnQuantity("");
    setReturnReason("");
    setBaseUnit("");
    txtSearch.setText("");
    setReturnAmount("");
    setPurchaseId("");
    setPurchaseQuantity("");
    //setStockQuantity("");
    setPurchaseAmount("");
}
public void setTextEditableTrue(){
   txtItemName.setEditable(true);
   txtStockQuantity.setEditable(true);
   txtDistributor.setEditable(true);
   txtBaseUnit.setEditable(true);
   txtPurchaseQuantity.setEditable(true);
   txtPurchaseAmount.setEditable(true);
}
public void setTextEditableFalse(){
    txtItemName.setEditable(false);
   txtStockQuantity.setEditable(false);
   txtDistributor.setEditable(false);
   txtBaseUnit.setEditable(false);
   txtPurchaseQuantity.setEditable(false);
   txtPurchaseAmount.setEditable(false);
    
}
public  String getSearch(){
    return txtSearch.getText().trim();
}
public void setSearch(String se){
    txtSearch.setText(se);
}
void addSearchListener(ActionListener ListenForSearch){
    btnSearch.addActionListener(ListenForSearch);
}
void addTextSearchListener(ActionListener ListenForSearch){
    txtSearch.addActionListener(ListenForSearch);
}
void addKeySearchlistener(KeyListener ListenForSearch){
    btnSearch.addKeyListener(ListenForSearch);
}
void addReturnListener(ActionListener ListenForReturn){
    btnReturn.addActionListener(ListenForReturn);
}
void addKeyReturnListener(KeyListener ListenForReturn){
    btnReturn.addKeyListener(ListenForReturn);
}
void addCancelListener(ActionListener ListerForCancel ){
    btnCancel.addActionListener(ListerForCancel);
}

void addKeyCancelListener(KeyListener ListenForCancel){
    btnCancel.addKeyListener(ListenForCancel);
}
void addSearchDocumentListener(DocumentListener Listen){
    txtSearch.getDocument().addDocumentListener(Listen);
}
void addSearchPropertyChangeListener(PropertyChangeListener Listen){
    txtSearch.addPropertyChangeListener("text", Listen);
}
void addRowSelectedListener(ListSelectionListener ListenForRow ){
    selectionModel.addListSelectionListener(ListenForRow);
}
public void refreshJTable(DefaultTableModel dataModel){
try {
   //  selectionModel  = tblItemList.getSelectionModel();
     //   selectionModel.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    tblItemList.setModel(dataModel);
    
}    
catch(ArrayIndexOutOfBoundsException aiob){
    //notthing to do
}
} 
public final class SetFocusListener implements FocusListener{
      JTextField jf;
        public SetFocusListener(JTextField field){
         jf = field;   
        }

        @Override
        public void focusGained(FocusEvent e) {
         //   throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
          jf.setBackground(new Color(136,249,168));
        }

        @Override
        public void focusLost(FocusEvent e) {
        //    throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
       jf.setBackground(Color.white);
        }
        
    }

    /**
     * @param args the command line arguments
     */
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnReturn;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDistributorName;
    private javax.swing.JLabel lblItemBaseUnit;
    private javax.swing.JLabel lblItemName;
    private javax.swing.JLabel lblReturnQuantity;
    private javax.swing.JLabel lblReturnReason;
    private javax.swing.JLabel lblStockQuantity;
    public javax.swing.JTable tblItemList;
    private javax.swing.JTextField txtBaseUnit;
    private javax.swing.JTextField txtDistributor;
    private javax.swing.JTextField txtItemName;
    private javax.swing.JTextField txtPurchaseAmount;
    private javax.swing.JTextField txtPurchaseQuantity;
    private javax.swing.JTextField txtReturnAmount;
    private javax.swing.JTextField txtReturnQuantity;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtStockQuantity;
    private javax.swing.JTextArea txtareaReturnReason;
    // End of variables declaration//GEN-END:variables
}
