/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package centerstore.itemunitentry;


import java.awt.Color;
import java.awt.event.ActionListener;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.sql.PreparedStatement;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.KeyStroke;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.TableModel;
import reusableClass.Function;

/**
 *
 * @author SUSHIL
 */
public class ItemUnitEntryView extends javax.swing.JDialog{
String strQuery;
private int UnitID;
PreparedStatement stmtdisplayJtable;

ListSelectionModel selectionModel;
String strSelectedRow[] ;
    /**
     * Creates new form ItemUnitView
     */
    public ItemUnitEntryView(JFrame parent,boolean modal) {
        super(parent,modal);
        initComponents();
          selectionModel  = tblUnitJTable.getSelectionModel();
        selectionModel.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        disableDeleteBtn();
        disableUpdateBtn();
        setButtonForEnter(btnAdd);
        setButtonForEnter(btnCancel);
        setButtonForEnter(btnDelete);
        setButtonForEnter(btnUpdate);
        txtUnitName.addFocusListener(new Function.SetTextFieldFocusListener(txtUnitName));
        txtUnitRelativeQuantity.addFocusListener(new Function.SetTextFieldFocusListener(txtUnitRelativeQuantity));
         /*
         * centering the frame
         */
        setLocationRelativeTo(null);
        
        
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblUnitName = new javax.swing.JLabel();
        txtUnitName = new javax.swing.JTextField();
        lblUnitType = new javax.swing.JLabel();
        comboUnitType = new javax.swing.JComboBox();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        txtUnitRelativeQuantity = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUnitJTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Unit Setup");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setMinimumSize(new java.awt.Dimension(505, 175));

        lblUnitName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblUnitName.setText("Unit Name");

        txtUnitName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblUnitType.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblUnitType.setText("Unit Type");

        comboUnitType.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comboUnitType.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"Select","ml", "piece","gm" }));
        comboUnitType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboUnitTypeActionPerformed(evt);
            }
        });

        btnAdd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAdd.setMnemonic('A');
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        btnAdd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnAddKeyPressed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnUpdate.setMnemonic('U');
        btnUpdate.setText("Update");

        btnDelete.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDelete.setMnemonic('D');
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnCancel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCancel.setMnemonic('C');
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        txtUnitRelativeQuantity.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtUnitRelativeQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUnitRelativeQuantityActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Item Relative Quantity");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblUnitName)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtUnitName))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtUnitRelativeQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblUnitType, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(comboUnitType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUnitName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUnitName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUnitRelativeQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUnitType, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboUnitType, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        tblUnitJTable.setAutoCreateRowSorter(true);
        tblUnitJTable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblUnitJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "UnitName", "Unit Relative Quantity", "Unit Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblUnitJTable.setFillsViewportHeight(true);
        tblUnitJTable.getTableHeader().setReorderingAllowed(false);
        tblUnitJTable.setRowHeight(20);
        jScrollPane1.setViewportView(tblUnitJTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelActionPerformed

    private void comboUnitTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboUnitTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboUnitTypeActionPerformed

    private void btnAddKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnAddKeyPressed
        // TODO add your handling code here:
       /*
        int code=evt.getKeyCode();
        if(code == KeyEvent.VK_ENTER){
            System.out.println("YOU enter add button");
        }
        * */
       // System.out.println(evt.getSource().equals("Add"));
    }//GEN-LAST:event_btnAddKeyPressed

    private void txtUnitRelativeQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUnitRelativeQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUnitRelativeQuantityActionPerformed
     public int getUnitID(){
        return UnitID;
    }
    public void setUnitID(int UnitID){
        this.UnitID = UnitID;
        
    }
    public String getUnitName(){
        return txtUnitName.getText();
        
    }
    public void setUnitName(String UnitName){
        txtUnitName.setText(UnitName);
    }
    
    public void clearAllText(){
        UnitID = 0;
        txtUnitName.setText("");
        txtUnitRelativeQuantity.setText("");
        /*try also to make ml as default combo type*/
        comboUnitType.setSelectedIndex(0);
       // JOptionPane.showMessageDialog(null, "this is test");
    }
    
    public int getUnitRelativeQuantity(){
        return Integer.parseInt(txtUnitRelativeQuantity.getText());
    }
    public void setUnitRelativeQuantity(String UnitRelativeQuantity){
        txtUnitRelativeQuantity.setText(UnitRelativeQuantity);
    }
    
    public String getUnitType(){
        return comboUnitType.getSelectedItem().toString();
    }
    public void SetUnitType(String UnitType) {
       // comboUnitType.setEditable(false);
        comboUnitType.setSelectedItem(UnitType);
       // comboUnitType.setSelectedItem("test");
    }
    public void enableAddBtn(){
        btnAdd.setEnabled(true);
    }
    public void disableAddBtn(){
        btnAdd.setEnabled(false);
    }
    public void enableUpdateBtn(){
        btnUpdate.setEnabled(true);
    }
    public void disableUpdateBtn(){
        btnUpdate.setEnabled(false);
    }
    public void enableDeleteBtn(){
        btnDelete.setEnabled(true);
    }
    public void disableDeleteBtn(){
        btnDelete.setEnabled(false);
    }
    
    void addAddListener(ActionListener ListenForAdd){
        btnAdd.addActionListener(ListenForAdd);
    }
    void addUpdateListener(ActionListener ListenForUpdate){
        btnUpdate.addActionListener(ListenForUpdate);
        
    }
    void addDeleteListener(ActionListener ListenForDelete){
        btnDelete.addActionListener(ListenForDelete);
        
    }
    void addCancelListener(ActionListener ListenForCancel){
        btnCancel.addActionListener(ListenForCancel);
    }
    void addRowSelectedListener(ListSelectionListener ListenForRowSelect){
       selectionModel.addListSelectionListener(ListenForRowSelect); 
    }
    void addKeyAddListener(KeyListener ListenForAdd){
        btnAdd.addKeyListener(ListenForAdd);
    }
    void addKeyUpdateListener(KeyListener ListenForUpdate){
        btnUpdate.addKeyListener(ListenForUpdate);
    }
    void addKeyDeleteListener(KeyListener ListenForDelete){
        btnDelete.addKeyListener(ListenForDelete);
    }
    void addKeyCancelListener(KeyListener ListenForCancel){
        btnCancel.addKeyListener(ListenForCancel);
    }
    void displayErrorMessage(String ErrorMessage){
        JOptionPane.showMessageDialog(this, ErrorMessage);
        
    }
     
     /**
     * It Set all the value from parameter to the respective textfield
     * @param UnitData 
     */
    void setUnitItem(String[] UnitData){
      
      setUnitID(Integer.parseInt(UnitData[0]));
      setUnitName(UnitData[1]);
     //JOptionPane.showMessageDialog(null, UnitData);
        
        setUnitRelativeQuantity(UnitData[2]);
        SetUnitType(UnitData[3]);
       // System.out.println(UnitData[3]);
       
       
        
    }
    public void refreshJTable(TableModel dataModel){
   
        
        try{
           // tblUnitJTable.setModel(new DefaultTableModel());
        tblUnitJTable.setModel(dataModel);
        
    }  
    
    catch(ArrayIndexOutOfBoundsException ae){
        System.out.println(ae+"fromrefreshtable");
    }
    
    }
    
   // void refreshJTable(DefaultTableModel dataModel){
        
    //}
    
    
    /**
     * return the selected item from the list
     * @param jb
     */
   
   /* public void valueChanged(ListSelectionEvent e){
        if(!e.getValueIsAdjusting()){
            ListSelectionModel model = tblUnitJTable.getSelectionModel();
            int lead = model.getLeadSelectionIndex();
           for(String test:displayRowValues(lead)){
            // return displayRowValues(lead)
               System.out.println(test);
           }
        }
    }
     private String[] displayRowValues(int rowIndex){
        int columns = tblUnitJTable.getColumnCount();
       // String s = "";
        
        String st[] = new String[columns];
        
        for(int col=0;col<columns;col++){
            Object o =tblUnitJTable.getValueAt(rowIndex, col);
          
           try{
                st[col] = o.toString();    
                }
            catch(NullPointerException e){
                System.err.println(e.getMessage());    
                }
        }
        
        return st;
    }
    */
     public void AddSelectInCombo(JComboBox jc){
      jc.insertItemAt("SELECT", 0);
      jc.setSelectedIndex(0);
    }
     public JComboBox returnComboUnitType(){
         return comboUnitType;
     }
     public final void setButtonForEnter(JButton jb){
         jb.registerKeyboardAction(jb.getActionForKeyStroke(
                                      KeyStroke.getKeyStroke(KeyEvent.VK_SPACE, 0, false)),
                                      KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0, false),
                                      JComponent.WHEN_FOCUSED);
 
        jb.registerKeyboardAction(jb.getActionForKeyStroke(
                                      KeyStroke.getKeyStroke(KeyEvent.VK_SPACE, 0, true)),
                                      KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0, true),
                                      JComponent.WHEN_FOCUSED);
        
    }
    public final class SetFocusListener implements FocusListener{
      JTextField jf;
        public SetFocusListener(JTextField field){
         jf = field;   
        }

        @Override
        public void focusGained(FocusEvent e) {
         //   throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        jf.setBackground(new Color(136,249,168));
        }

        @Override
        public void focusLost(FocusEvent e) {
        //    throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
       jf.setBackground(Color.white);
        }
        
    }
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ItemUnitEntryView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ItemUnitEntryView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ItemUnitEntryView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ItemUnitEntryView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ItemUnitEntryView(new JFrame(),true).setVisible(true);
                
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox comboUnitType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblUnitName;
    private javax.swing.JLabel lblUnitType;
    public javax.swing.JTable tblUnitJTable;
    private javax.swing.JTextField txtUnitName;
    private javax.swing.JTextField txtUnitRelativeQuantity;
    // End of variables declaration//GEN-END:variables
}

