/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserCrud;

import java.awt.KeyEventDispatcher;
import java.awt.KeyboardFocusManager;
import java.awt.event.ActionListener;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import reusableClass.Function;

/**
 *
 * @author SUSHIL
 */
public class UserCrudView extends javax.swing.JDialog {
    private final ListSelectionModel listmodel;
    private  int UserId = 0;
    private int Departmentid=0;
    private String EncryptedPassword = null;
    private String DecryptedPasword = null;
     //listening through the keyboard shortcut
    private KeyboardFocusManager kfmanager;

    /**
     * Creates new form UserCrudView
     * @param parent
     * @param modal
     */
    public UserCrudView(JFrame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        btnViewPassword.setVisible(false);
        Function.setButtonForEnter(btnAdd);
        Function.setButtonForEnter(btnEdit);
        Function.setButtonForEnter(btnDelete);
        Function.setButtonForEnter(btnCancel);
        Function.setButtonForEnter(btnChangePassword);
        Function.setButtonForEnter(btnViewPassword);
        listmodel = tblUserInfo.getSelectionModel();
        listmodel.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        txtPassword.addFocusListener(new Function.SetTextFieldFocusListener(txtPassword));
        txtUserName.addFocusListener(new Function.SetTextFieldFocusListener(txtUserName));
        txtConfirmPassword.addFocusListener(new Function.SetTextFieldFocusListener(txtConfirmPassword));
        kfmanager = KeyboardFocusManager.getCurrentKeyboardFocusManager();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUserName = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUserInfo = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        comboDepartment = new javax.swing.JComboBox();
        panelPasswordField = new javax.swing.JPanel();
        txtConfirmPassword = new javax.swing.JPasswordField();
        lblConfirmPassword = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        panelPasswordButton = new javax.swing.JPanel();
        btnViewPassword = new javax.swing.JButton();
        btnChangePassword = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("User Authority Window");

        txtUserName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnAdd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAdd.setMnemonic('A');
        btnAdd.setText("Add");

        btnEdit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnEdit.setMnemonic('E');
        btnEdit.setText("Edit");
        btnEdit.setEnabled(false);

        btnDelete.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDelete.setMnemonic('D');
        btnDelete.setText("Delete");
        btnDelete.setEnabled(false);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnCancel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCancel.setMnemonic('C');
        btnCancel.setText("Cancel");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("UserName:");

        jScrollPane1.setViewportView(tblUserInfo);
        tblUserInfo.getTableHeader().setReorderingAllowed(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Assign Department:");

        comboDepartment.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblConfirmPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblConfirmPassword.setText("Confirm Password:");

        lblPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPassword.setText("Password:");

        javax.swing.GroupLayout panelPasswordFieldLayout = new javax.swing.GroupLayout(panelPasswordField);
        panelPasswordField.setLayout(panelPasswordFieldLayout);
        panelPasswordFieldLayout.setHorizontalGroup(
            panelPasswordFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPasswordFieldLayout.createSequentialGroup()
                .addGroup(panelPasswordFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(panelPasswordFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtConfirmPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .addComponent(txtPassword)))
        );

        panelPasswordFieldLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblConfirmPassword, lblPassword});

        panelPasswordFieldLayout.setVerticalGroup(
            panelPasswordFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPasswordFieldLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(panelPasswordFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPasswordFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblConfirmPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        panelPasswordFieldLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblConfirmPassword, lblPassword});

        btnViewPassword.setText("View Password");
        btnViewPassword.setActionCommand("ViewPassword");

        btnChangePassword.setText("Change Password");
        btnChangePassword.setActionCommand("ChangePassword");

        javax.swing.GroupLayout panelPasswordButtonLayout = new javax.swing.GroupLayout(panelPasswordButton);
        panelPasswordButton.setLayout(panelPasswordButtonLayout);
        panelPasswordButtonLayout.setHorizontalGroup(
            panelPasswordButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPasswordButtonLayout.createSequentialGroup()
                .addGroup(panelPasswordButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnChangePassword)
                    .addComponent(btnViewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        panelPasswordButtonLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnChangePassword, btnViewPassword});

        panelPasswordButtonLayout.setVerticalGroup(
            panelPasswordButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPasswordButtonLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnChangePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnViewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(35, 35, 35)
                                .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(panelPasswordButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 155, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(panelPasswordButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboDepartment))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed
    public void setUserName(String name){
        txtUserName.setText(name);
    }
    public String getUserName(){
        return txtUserName.getText().trim();
    }
    public void setPassWord(String pass){
        txtPassword.setText(pass);
    }
    public char[] getPassWord(){
        return txtPassword.getPassword();
    }
    public void setConfirmPassword(String pass){
        txtConfirmPassword.setText(pass);
    }
    public char[] getConfirmPassword(){
        return txtConfirmPassword.getPassword();
    }
    public void setUserId(int id){
        UserId = id;
    }
    public int getUserId(){
        return UserId;
    }
     public void setDepartmentId(int id){
        Departmentid = id;
    }
    public int getDepartmentId(){
        return Departmentid;
    }

    public String getEncryptedPassword() {
        return EncryptedPassword;
    }

    public void setEncryptedPassword(String EncryptedPassword) {
        this.EncryptedPassword = EncryptedPassword;
    }

    public String getDecryptedPasword() {
        return DecryptedPasword;
    }

    public void setDecryptedPasword(String DecryptedPasword) {
        this.DecryptedPasword = DecryptedPasword;
    }
    
    public void refreshJTableUserInfo(DefaultTableModel model){
        tblUserInfo.setModel(model);
    }
    public void setcomboDepartment(String st){
        comboDepartment.setSelectedItem(st);
    }
    public void setcomboDepartment(Object[] st){
        DefaultComboBoxModel model = new DefaultComboBoxModel(st);
        comboDepartment.setModel(model);
    }
    public String getcomboDepartment(){
        return comboDepartment.getSelectedItem().toString();
    }
    public JComboBox returncomboDepartment(){
        return comboDepartment;
    }
     public void AddSelectInCombo(JComboBox jc){
      jc.insertItemAt("SELECT", 0);
      jc.setSelectedIndex(0);
    }
    public DefaultTableModel getJtableUserInfo(){
        return (DefaultTableModel)tblUserInfo.getModel();
    }
    public void addAddListener(ActionListener Listen){
        btnAdd.addActionListener(Listen);
    }
    public void addEditListener(ActionListener Listen){
        btnEdit.addActionListener(Listen);
    }
    public void addDeleteListener(ActionListener Listen){
        btnDelete.addActionListener(Listen);
    }
    public void addCancelListener(ActionListener Listen){
        btnCancel.addActionListener(Listen);
    }
    public void addUserListSelectionListener(ListSelectionListener Listen){
        listmodel.addListSelectionListener(Listen);
    }
    public void addcomboDepartmentListener(ActionListener listen){
        comboDepartment.addActionListener(listen);
    }
    public void addChangePasswordListener(ActionListener Listen){
        btnChangePassword.addActionListener(Listen);
    }
    public void addViewPasswordListener(ActionListener Listen){
        btnViewPassword.addActionListener(Listen);
    }
    //adding delaget for listening fore keyboard shortcut through out the frame
     public void addShortcutForUserCrud(KeyEventDispatcher Listen){
         kfmanager.addKeyEventDispatcher(Listen);
     }
    public void setbtnAddEnableTrue(){
        btnAdd.setEnabled(true);
    }
    public void setbtnAddEnableFalse(){
        btnAdd.setEnabled(false);
    }
     public void setbtnEditEnableTrue(){
        btnEdit.setEnabled(true);
    }
    public void setbtnEditEnableFalse(){
        btnEdit.setEnabled(false);
    }
     public void setbtnDeleteEnableTrue(){
        btnDelete.setEnabled(true);
    }
    public void setbtnDeleteEnableFalse(){
        btnDelete.setEnabled(false);
    }
     public void setbtnCancelEnableTrue(){
        btnCancel.setEnabled(true);
    }
    public void setbtnCancelEnableFalse(){
        btnCancel.setEnabled(false);
    }

    //return jtable and username
    public JTable getTblUserInfo() {
        return tblUserInfo;
    }

    public JTextField getTxtUserName() {
        return txtUserName;
    }
    
    
    public void setPasswordFieldsVisible(boolean bl){
       lblConfirmPassword.setVisible(bl);
       lblPassword.setVisible(bl);
       txtConfirmPassword.setVisible(bl);
       txtPassword.setVisible(bl);
    }
    public void setBtnChangePasswordVisible(boolean bl){
        btnChangePassword.setVisible(bl);
        
    }
    public void setBtnViewPasswordVisible(boolean bl){
        btnViewPassword.setVisible(bl);
    }
    public void setPanelPasswordButtonVisible(boolean bl){
        panelPasswordButton.setVisible(bl);
    }
    public void setPanelPasswordFieldsVisible(boolean bl){
       panelPasswordField.setVisible(bl);
    }
    
    
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    public javax.swing.JButton btnCancel;
    private javax.swing.JButton btnChangePassword;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnViewPassword;
    private javax.swing.JComboBox comboDepartment;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblConfirmPassword;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JPanel panelPasswordButton;
    private javax.swing.JPanel panelPasswordField;
    public javax.swing.JTable tblUserInfo;
    private javax.swing.JPasswordField txtConfirmPassword;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
