/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelmanagementsystem;

import java.awt.Component;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.SwingConstants;
import java.util.Calendar;
import java.util.GregorianCalendar;

/**
 *
 * @author SUSHIL
 */
public class MainFrameView extends javax.swing.JFrame {
    private final JMenuItem PopUpMenuItemSalesReport ;
    private final JMenuItem PopUPMenuItemItemWiseSalesReport;
    private final JMenuItem PopUpMenuItemIssueReport;
    private final JMenuItem PopUpMenuItemIssueStockReport;
//    public JDesktopPane desktop ;
    private   int countforpay =0;
    private  int countfororder =0;
    private int countfortablestatus =0;
    private int countfordirectpay = 0;
    private int UserId = 0;
//    JScrollPane testscrollpane ;
    

    /**
     * Creates new form MainFrameView
     */
    public MainFrameView() {
//          desktop = new JDesktopPane();
       
      
        
        initComponents();
//        testscrollpane = new JScrollPane();
      
//        jToolBar1.setBackground(new Color(204, 204, 255));
        jToolBar1.setOpaque(true);
//        getContentPane().add(desktop);
//        btnOrder.setFocusPainted(false);
//         desktop.setPreferredSize(new Dimension(500,585));
//         
//        DesktopPanel.setLayout(new BorderLayout());
//         DesktopPanel.add(desktop);
//           testscrollpane.setViewportView(DesktopPanel);
        
        
        /*
         * setting desktop pane for internal frame
         */
//      
//        JInternalFrame frame = new JInternalFrame("test",true,true,true,true);
//        frame.setVisible(true);
//        desktop.add(frame);
//         frame.setSize(200,200);
       
         PopUpMenuItemIssueStockReport = new JMenuItem("Issue Stock Report");
         PopUpMenuItemIssueStockReport.setActionCommand("IssueStockReport");
         PopUPMenuItemItemWiseSalesReport = new JMenuItem("Item Wise Sales Report");
        /*
         * actioncommand same as in menuitem top level
         */
        PopUPMenuItemItemWiseSalesReport.setActionCommand("ItemWiseSalesReport");
        PopUpMenuItemSalesReport = new JMenuItem("Bill Wise Sales Report");
        PopUpMenuItemSalesReport.setActionCommand("SalesReport");
        PopUpMenuItemIssueReport = new JMenuItem("Issue/Return Report");
        PopUpMenuItemIssueReport.setActionCommand("TerminalItemwiseIssue/ReturnReport");
        
        setExtendedState(MAXIMIZED_BOTH);
        setLogOutVisibleFalse();
        setChangePasswordVisible(false);
       
    
//        btnReport.addMouseListener(new MouseAdapter(){
//            public void mouseReleased(MouseEvent me){
//                
//              ReportPopUpMenu.show(me.getComponent(), me.getX(), me.getY());            }
//        });
      /*
       * adding popupmenu
       */
        AddToPopUpMenu();
        //running the clock
        StartClock();
//        getAllMenuItemText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        ReportPopUpMenu = new javax.swing.JPopupMenu();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jSeparator26 = new javax.swing.JToolBar.Separator();
        btnOrder = new javax.swing.JButton();
        jSeparator11 = new javax.swing.JToolBar.Separator();
        btnPay = new javax.swing.JButton();
        jSeparator12 = new javax.swing.JToolBar.Separator();
        btnTableStatus = new javax.swing.JButton();
        jSeparator29 = new javax.swing.JToolBar.Separator();
        btnMenuDetailView = new javax.swing.JButton();
        jSeparator33 = new javax.swing.JToolBar.Separator();
        btnReport = new javax.swing.JButton();
        jSeparator25 = new javax.swing.JToolBar.Separator();
        btnAboutUs = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        desktop = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblusername = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblCompanyName = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblPhoneNumber = new javax.swing.JLabel();
        ImageLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblClock = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblDayStatus = new javax.swing.JLabel();
        jSeparator46 = new javax.swing.JSeparator();
        btnDreamsys = new javax.swing.JButton();
        btnChangePassword = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuItemCompanySetup = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        MenuItemCustomerSetup = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        MenuItemDistributorSetup = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        MenuItemWaiterSetup = new javax.swing.JMenuItem();
        jSeparator49 = new javax.swing.JPopupMenu.Separator();
        MenuItemRegistration = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        MenuItemUnitSetup = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        MenuItemGroupSetup = new javax.swing.JMenuItem();
        centerstore = new javax.swing.JMenu();
        MenuItemEntry = new javax.swing.JMenuItem();
        jSeparator32 = new javax.swing.JPopupMenu.Separator();
        MenuItemItemLot = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        MenuItemIssue = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        MenuitemPurchaseReturn = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        MenuItemMenuEntry = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        MenuItemTableSetup = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        MenuItemThresholdSetup = new javax.swing.JMenuItem();
        jSeparator45 = new javax.swing.JPopupMenu.Separator();
        MenuItemComplimentaryReasonSetup = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        MenuItemOrder = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        MenuItemPay = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        MenuItemTableStatus = new javax.swing.JMenuItem();
        jSeparator28 = new javax.swing.JPopupMenu.Separator();
        jMenu7 = new javax.swing.JMenu();
        MenuItemMenuView = new javax.swing.JMenuItem();
        MenuItemDetailView = new javax.swing.JMenuItem();
        jSeparator30 = new javax.swing.JPopupMenu.Separator();
        MenuItemIssueReturn = new javax.swing.JMenuItem();
        jSeparator31 = new javax.swing.JPopupMenu.Separator();
        MenuItemDirectBillPay = new javax.swing.JMenuItem();
        jSeparator16 = new javax.swing.JPopupMenu.Separator();
        MenuItemVoidBill = new javax.swing.JMenuItem();
        jSeparator43 = new javax.swing.JPopupMenu.Separator();
        MenuItemWastage = new javax.swing.JMenuItem();
        jSeparator44 = new javax.swing.JPopupMenu.Separator();
        MenuItemCreditPayment = new javax.swing.JMenuItem();
        jSeparator47 = new javax.swing.JPopupMenu.Separator();
        jMenu2 = new javax.swing.JMenu();
        MenuItemItemReport = new javax.swing.JMenuItem();
        jSeparator21 = new javax.swing.JPopupMenu.Separator();
        MenuItemPurchaseReport = new javax.swing.JMenuItem();
        jSeparator22 = new javax.swing.JPopupMenu.Separator();
        MenuItemPurchaseReturnReport = new javax.swing.JMenuItem();
        jSeparator23 = new javax.swing.JPopupMenu.Separator();
        MenuItemDistributorReport = new javax.swing.JMenuItem();
        jSeparator24 = new javax.swing.JPopupMenu.Separator();
        jMenu11 = new javax.swing.JMenu();
        MenuItemCenterstoreItemWiseIssueReport = new javax.swing.JMenuItem();
        jSeparator41 = new javax.swing.JPopupMenu.Separator();
        MenuItemCenterstoreCategoryIssueReport = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        MenuItemIssueStockReport = new javax.swing.JMenuItem();
        jSeparator27 = new javax.swing.JPopupMenu.Separator();
        MenuItemSalesReport = new javax.swing.JMenuItem();
        jSeparator13 = new javax.swing.JPopupMenu.Separator();
        MenuItemItemWiseSalesReport = new javax.swing.JMenuItem();
        jSeparator14 = new javax.swing.JPopupMenu.Separator();
        MenuItemReceivableReport = new javax.swing.JMenuItem();
        jSeparator15 = new javax.swing.JPopupMenu.Separator();
        jMenu10 = new javax.swing.JMenu();
        TerminalMenuItemIssueReport = new javax.swing.JMenuItem();
        jSeparator40 = new javax.swing.JPopupMenu.Separator();
        TerminalMenuCategoryIssueReport = new javax.swing.JMenuItem();
        jSeparator17 = new javax.swing.JPopupMenu.Separator();
        MenuItemSVCReport = new javax.swing.JMenuItem();
        jSeparator18 = new javax.swing.JPopupMenu.Separator();
        MenuItemVATReport = new javax.swing.JMenuItem();
        jSeparator36 = new javax.swing.JPopupMenu.Separator();
        MenuItemDiscountReport = new javax.swing.JMenuItem();
        jSeparator19 = new javax.swing.JPopupMenu.Separator();
        MenuItemComplimentaryReport = new javax.swing.JMenuItem();
        jSeparator20 = new javax.swing.JPopupMenu.Separator();
        MenuItemWaiterServiceReport = new javax.swing.JMenuItem();
        jSeparator42 = new javax.swing.JPopupMenu.Separator();
        MenuItemVoidReport = new javax.swing.JMenuItem();
        jSeparator35 = new javax.swing.JPopupMenu.Separator();
        MenuItemMenuList = new javax.swing.JMenuItem();
        jSeparator48 = new javax.swing.JPopupMenu.Separator();
        MenuItemWastageReport = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        MenuItemSystemDateConfig = new javax.swing.JMenuItem();
        jSeparator37 = new javax.swing.JPopupMenu.Separator();
        MenuItemSystemDateOpen = new javax.swing.JMenuItem();
        jSeparator38 = new javax.swing.JPopupMenu.Separator();
        MenuItemSystemDateClose = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        MenuItemUserCreditial = new javax.swing.JMenuItem();
        jSeparator34 = new javax.swing.JPopupMenu.Separator();
        MenuItemMangeUser = new javax.swing.JMenuItem();
        jSeparator39 = new javax.swing.JPopupMenu.Separator();
        MenuItemDepartmentSetup = new javax.swing.JMenuItem();

        jDialog1.setModal(true);

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        ReportPopUpMenu.setBackground(new java.awt.Color(0, 204, 204));

        //JMenuItem menuitem = new JMenuItem("tes");
        //ReportPopUpMenu.add(menuitem);
        //menuitem = new JMenuItem("Sucessfull");
        //ReportPopUpMenu.add(menuitem);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("DreamSYS Point Of Sale");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/images/imageorder.png")).getImage());
        setMinimumSize(new java.awt.Dimension(1000, 800));

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(false);
        jToolBar1.setMaximumSize(new java.awt.Dimension(390, 58));
        jToolBar1.add(jSeparator26);

        btnOrder.setBackground(new java.awt.Color(255, 255, 255));
        btnOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imageorder1.png"))); // NOI18N
        btnOrder.setText("Order");
        btnOrder.setMaximumSize(new java.awt.Dimension(117, 40));
        btnOrder.setMinimumSize(new java.awt.Dimension(117, 40));
        //jButton1.setHorizontalTextPosition(SwingConstants.BOTTOM);
        jToolBar1.add(btnOrder);
        btnOrder.setHorizontalTextPosition(SwingConstants.CENTER);
        btnOrder.setVerticalTextPosition(SwingConstants.BOTTOM);
        jToolBar1.add(jSeparator11);

        btnPay.setBackground(new java.awt.Color(255, 255, 255));
        btnPay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/payimage1.png"))); // NOI18N
        btnPay.setText("Pay");
        btnPay.setMaximumSize(new java.awt.Dimension(69, 40));
        btnPay.setMinimumSize(new java.awt.Dimension(69, 40));
        //jButton1.setHorizontalTextPosition(SwingConstants.BOTTOM);
        btnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPay);
        btnPay.setHorizontalTextPosition(SwingConstants.CENTER);
        btnPay.setVerticalTextPosition(SwingConstants.BOTTOM);
        jToolBar1.add(jSeparator12);

        btnTableStatus.setBackground(new java.awt.Color(255, 255, 255));
        btnTableStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tableview1.png"))); // NOI18N
        btnTableStatus.setText("Table Status");
        btnTableStatus.setActionCommand("TableStatus");
        btnTableStatus.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTableStatus.setMaximumSize(new java.awt.Dimension(69, 40));
        btnTableStatus.setMinimumSize(new java.awt.Dimension(69, 40));
        btnTableStatus.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        //jButton1.setHorizontalTextPosition(SwingConstants.BOTTOM);
        btnTableStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTableStatusActionPerformed(evt);
            }
        });
        jToolBar1.add(btnTableStatus);
        btnPay.setHorizontalTextPosition(SwingConstants.CENTER);
        btnPay.setVerticalTextPosition(SwingConstants.BOTTOM);
        jToolBar1.add(jSeparator29);

        btnMenuDetailView.setBackground(new java.awt.Color(255, 255, 255));
        btnMenuDetailView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menuview.png"))); // NOI18N
        btnMenuDetailView.setText("Menu View");
        btnMenuDetailView.setActionCommand("MenuDetailView");
        btnMenuDetailView.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMenuDetailView.setMaximumSize(new java.awt.Dimension(69, 40));
        btnMenuDetailView.setMinimumSize(new java.awt.Dimension(69, 40));
        btnMenuDetailView.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        //jButton1.setHorizontalTextPosition(SwingConstants.BOTTOM);
        btnMenuDetailView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuDetailViewActionPerformed(evt);
            }
        });
        jToolBar1.add(btnMenuDetailView);
        btnPay.setHorizontalTextPosition(SwingConstants.CENTER);
        btnPay.setVerticalTextPosition(SwingConstants.BOTTOM);
        jToolBar1.add(jSeparator33);

        btnReport.setBackground(new java.awt.Color(255, 255, 255));
        btnReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/report1.png"))); // NOI18N
        btnReport.setText("Report");
        btnReport.setMaximumSize(new java.awt.Dimension(83, 40));
        btnReport.setMinimumSize(new java.awt.Dimension(83, 40));
        //jButton1.setHorizontalTextPosition(SwingConstants.BOTTOM);
        btnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportActionPerformed(evt);
            }
        });
        jToolBar1.add(btnReport);
        btnReport.setHorizontalTextPosition(SwingConstants.CENTER);
        btnReport.setVerticalTextPosition(SwingConstants.BOTTOM);
        jToolBar1.add(jSeparator25);

        btnAboutUs.setBackground(new java.awt.Color(255, 255, 255));
        btnAboutUs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/aboutus1.png"))); // NOI18N
        btnAboutUs.setText("About Us");
        btnAboutUs.setActionCommand("AboutUs");
        btnAboutUs.setMaximumSize(new java.awt.Dimension(95, 40));
        btnAboutUs.setMinimumSize(new java.awt.Dimension(95, 40));
        //jButton1.setHorizontalTextPosition(SwingConstants.BOTTOM);
        btnAboutUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAboutUsActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAboutUs);
        btnAboutUs.setHorizontalTextPosition(SwingConstants.CENTER);
        btnAboutUs.setVerticalTextPosition(SwingConstants.BOTTOM);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dream_web.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, desktopLayout.createSequentialGroup()
                .addContainerGap(978, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, desktopLayout.createSequentialGroup()
                .addContainerGap(389, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        desktop.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane1.setViewportView(desktop);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Welcome,");

        lblusername.setForeground(new java.awt.Color(102, 153, 255));

        btnLogOut.setForeground(new java.awt.Color(102, 153, 255));
        btnLogOut.setText("Log Out");
        btnLogOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jPanel2.setMaximumSize(new java.awt.Dimension(32767, 58));

        lblCompanyName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblCompanyName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblAddress.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAddress.setMinimumSize(new java.awt.Dimension(0, 14));

        lblPhoneNumber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPhoneNumber.setMinimumSize(new java.awt.Dimension(0, 14));

        ImageLabel.setMaximumSize(new java.awt.Dimension(100, 55));

        jPanel3.setDoubleBuffered(false);
        jPanel3.setEnabled(false);

        lblClock.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        lblClock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblDate.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblClock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDayStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(lblDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1)
                .addComponent(lblClock, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(lblDayStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jSeparator46.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator46, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblPhoneNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                        .addComponent(lblAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblCompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblAddress, lblCompanyName, lblPhoneNumber});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblCompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(lblAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(0, 0, 0)
                        .addComponent(lblPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jSeparator46, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnDreamsys.setBackground(new java.awt.Color(204, 204, 204));
        btnDreamsys.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnDreamsys.setForeground(new java.awt.Color(102, 153, 255));
        btnDreamsys.setText("Point Of Sales@DreamSYS IT Solution");
        btnDreamsys.setAlignmentY(0.0F);
        btnDreamsys.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDreamsys.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnDreamsys.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDreamsysActionPerformed(evt);
            }
        });

        btnChangePassword.setForeground(new java.awt.Color(153, 0, 0));
        btnChangePassword.setText("Change Password");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblusername, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(btnLogOut)
                        .addGap(18, 18, 18)
                        .addComponent(btnChangePassword)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDreamsys))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnLogOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnChangePassword))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblusername, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDreamsys, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jToolBar1.addSeparator();

        jScrollPane2.setViewportView(jPanel1);

        jMenuBar2.setToolTipText("");
        jMenuBar2.setAlignmentY(0.5F);
        jMenuBar2.setAutoscrolls(true);

        jMenu1.setMnemonic('C');
        jMenu1.setText("Company Setup");

        MenuItemCompanySetup.setText("Company Setup");
        MenuItemCompanySetup.setActionCommand("CompanySetup");
        jMenu1.add(MenuItemCompanySetup);
        jMenu1.add(jSeparator8);

        MenuItemCustomerSetup.setText("Customer Setup");
        MenuItemCustomerSetup.setActionCommand("CustomerSetup");
        MenuItemCustomerSetup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemCustomerSetupActionPerformed(evt);
            }
        });
        jMenu1.add(MenuItemCustomerSetup);
        jMenu1.add(jSeparator9);

        MenuItemDistributorSetup.setText("Distributor Setup");
        MenuItemDistributorSetup.setActionCommand("DistributorSetup");
        MenuItemDistributorSetup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemDistributorSetupActionPerformed(evt);
            }
        });
        jMenu1.add(MenuItemDistributorSetup);
        jMenu1.add(jSeparator10);

        MenuItemWaiterSetup.setText("Waiter Setup");
        MenuItemWaiterSetup.setActionCommand("WaiterSetup");
        MenuItemWaiterSetup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemWaiterSetupActionPerformed(evt);
            }
        });
        jMenu1.add(MenuItemWaiterSetup);
        jMenu1.add(jSeparator49);

        MenuItemRegistration.setText("Software Registration");
        MenuItemRegistration.setActionCommand("SoftwareRegistration");
        jMenu1.add(MenuItemRegistration);

        jMenuBar2.add(jMenu1);

        jMenu3.setMnemonic('B');
        jMenu3.setText("Basic Setup");
        jMenu3.setToolTipText("Ctrl +B");
        jMenu3.setActionCommand("BasicSetup");

        MenuItemUnitSetup.setText("Unit Setup");
        MenuItemUnitSetup.setActionCommand("UnitSetup");
        jMenu3.add(MenuItemUnitSetup);
        jMenu3.add(jSeparator7);

        MenuItemGroupSetup.setText("Group & Category Setup");
        MenuItemGroupSetup.setActionCommand("Group&CategorySetup");
        MenuItemGroupSetup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemGroupSetupActionPerformed(evt);
            }
        });
        jMenu3.add(MenuItemGroupSetup);

        jMenuBar2.add(jMenu3);

        centerstore.setMnemonic('C');
        centerstore.setText("CenterStore");

        MenuItemEntry.setText("Item Entry/Purchase");
        MenuItemEntry.setActionCommand("ItemEntry");
        centerstore.add(MenuItemEntry);
        centerstore.add(jSeparator32);

        MenuItemItemLot.setText("Item Add/Item Lot");
        MenuItemItemLot.setActionCommand("ItemAdd/ItemLot");
        centerstore.add(MenuItemItemLot);
        centerstore.add(jSeparator5);

        MenuItemIssue.setText("Issue");
        MenuItemIssue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemIssueActionPerformed(evt);
            }
        });
        centerstore.add(MenuItemIssue);
        centerstore.add(jSeparator6);

        MenuitemPurchaseReturn.setText("Purchase Return");
        MenuitemPurchaseReturn.setActionCommand("PurchaseReturn");
        centerstore.add(MenuitemPurchaseReturn);

        jMenuBar2.add(centerstore);

        jMenu4.setMnemonic('T');
        jMenu4.setText("Terminal Setup");

        MenuItemMenuEntry.setText("MenuEntry");
        jMenu4.add(MenuItemMenuEntry);
        jMenu4.add(jSeparator3);

        MenuItemTableSetup.setText("TableSetup");
        MenuItemTableSetup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemTableSetupActionPerformed(evt);
            }
        });
        jMenu4.add(MenuItemTableSetup);
        jMenu4.add(jSeparator4);

        MenuItemThresholdSetup.setText("ThresholdSetup");
        jMenu4.add(MenuItemThresholdSetup);
        jMenu4.add(jSeparator45);

        MenuItemComplimentaryReasonSetup.setText("Complimentary Reason Setup");
        MenuItemComplimentaryReasonSetup.setActionCommand("ComplimentaryReasonSetup");
        jMenu4.add(MenuItemComplimentaryReasonSetup);

        jMenuBar2.add(jMenu4);

        jMenu6.setMnemonic('T');
        jMenu6.setText("Terminal");

        MenuItemOrder.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_MASK));
        MenuItemOrder.setText("Order");
        jMenu6.add(MenuItemOrder);
        jMenu6.add(jSeparator1);

        MenuItemPay.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        MenuItemPay.setText("Pay");
        jMenu6.add(MenuItemPay);
        jMenu6.add(jSeparator2);

        MenuItemTableStatus.setText("Table Status");
        MenuItemTableStatus.setActionCommand("TableStatus");
        jMenu6.add(MenuItemTableStatus);
        jMenu6.add(jSeparator28);

        jMenu7.setText("Menu List");

        MenuItemMenuView.setText("Menu View");
        MenuItemMenuView.setActionCommand("MenuView");
        jMenu7.add(MenuItemMenuView);

        MenuItemDetailView.setText("Menu Detail View");
        MenuItemDetailView.setActionCommand("MenuDetailView");
        jMenu7.add(MenuItemDetailView);

        jMenu6.add(jMenu7);
        jMenu6.add(jSeparator30);

        MenuItemIssueReturn.setText("IssueReturn");
        jMenu6.add(MenuItemIssueReturn);
        jMenu6.add(jSeparator31);

        MenuItemDirectBillPay.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        MenuItemDirectBillPay.setText("Direct Bill Pay");
        MenuItemDirectBillPay.setActionCommand("DirectBillPay");
        jMenu6.add(MenuItemDirectBillPay);
        jMenu6.add(jSeparator16);

        MenuItemVoidBill.setText("Void Bill");
        MenuItemVoidBill.setActionCommand("VoidBill");
        jMenu6.add(MenuItemVoidBill);
        jMenu6.add(jSeparator43);

        MenuItemWastage.setText("Wastage");
        jMenu6.add(MenuItemWastage);
        jMenu6.add(jSeparator44);

        MenuItemCreditPayment.setText("Credit Payment");
        MenuItemCreditPayment.setActionCommand("CreditPayment");
        jMenu6.add(MenuItemCreditPayment);
        jMenu6.add(jSeparator47);

        jMenuBar2.add(jMenu6);

        jMenu2.setMnemonic('C');
        jMenu2.setText("CenterStore Report");

        MenuItemItemReport.setText("Item Report");
        MenuItemItemReport.setActionCommand("ItemReport");
        jMenu2.add(MenuItemItemReport);
        jMenu2.add(jSeparator21);

        MenuItemPurchaseReport.setText("Purchase Report");
        MenuItemPurchaseReport.setActionCommand("PurchaseReport");
        jMenu2.add(MenuItemPurchaseReport);
        jMenu2.add(jSeparator22);

        MenuItemPurchaseReturnReport.setText("Purchase Return Report");
        MenuItemPurchaseReturnReport.setActionCommand("PurchaseReturnReport");
        MenuItemPurchaseReturnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemPurchaseReturnReportActionPerformed(evt);
            }
        });
        jMenu2.add(MenuItemPurchaseReturnReport);
        jMenu2.add(jSeparator23);

        MenuItemDistributorReport.setText("Distributor Report");
        MenuItemDistributorReport.setActionCommand("DistributorReport");
        jMenu2.add(MenuItemDistributorReport);
        jMenu2.add(jSeparator24);

        jMenu11.setText("Centerstore Issue Report");

        MenuItemCenterstoreItemWiseIssueReport.setText("Itemwise");
        MenuItemCenterstoreItemWiseIssueReport.setActionCommand("CenterstoreItemwiseIssue/ReturnReport");
        MenuItemCenterstoreItemWiseIssueReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemCenterstoreItemWiseIssueReportActionPerformed(evt);
            }
        });
        jMenu11.add(MenuItemCenterstoreItemWiseIssueReport);
        jMenu11.add(jSeparator41);

        MenuItemCenterstoreCategoryIssueReport.setText("Categorywise");
        MenuItemCenterstoreCategoryIssueReport.setActionCommand("CenterstoreCategorywiseIssue/ReturnReport");
        jMenu11.add(MenuItemCenterstoreCategoryIssueReport);

        jMenu2.add(jMenu11);

        jMenuBar2.add(jMenu2);

        jMenu5.setMnemonic('T');
        jMenu5.setText("Terminal Report");

        MenuItemIssueStockReport.setText("Issue Stock Report");
        MenuItemIssueStockReport.setActionCommand("IssueStockReport");
        jMenu5.add(MenuItemIssueStockReport);
        jMenu5.add(jSeparator27);

        MenuItemSalesReport.setText("Sales Report");
        MenuItemSalesReport.setActionCommand("SalesReport");
        jMenu5.add(MenuItemSalesReport);
        jMenu5.add(jSeparator13);

        MenuItemItemWiseSalesReport.setText("ItemWise Sales Report");
        MenuItemItemWiseSalesReport.setActionCommand("ItemWiseSalesReport");
        jMenu5.add(MenuItemItemWiseSalesReport);
        jMenu5.add(jSeparator14);

        MenuItemReceivableReport.setText("Receivable Report");
        MenuItemReceivableReport.setActionCommand("ReceivableReport");
        jMenu5.add(MenuItemReceivableReport);
        jMenu5.add(jSeparator15);

        jMenu10.setText("Issue Report");

        TerminalMenuItemIssueReport.setText("Itemwise");
        TerminalMenuItemIssueReport.setActionCommand("TerminalItemwiseIssue/ReturnReport");
        jMenu10.add(TerminalMenuItemIssueReport);
        jMenu10.add(jSeparator40);

        TerminalMenuCategoryIssueReport.setText("Categorywise");
        TerminalMenuCategoryIssueReport.setActionCommand("TerminalCategorywiseIssue/ReturnReport");
        jMenu10.add(TerminalMenuCategoryIssueReport);

        jMenu5.add(jMenu10);
        jMenu5.add(jSeparator17);

        MenuItemSVCReport.setText("SVCReport");
        jMenu5.add(MenuItemSVCReport);
        jMenu5.add(jSeparator18);

        MenuItemVATReport.setText("VATReport");
        jMenu5.add(MenuItemVATReport);
        jMenu5.add(jSeparator36);

        MenuItemDiscountReport.setText("Discount Report");
        MenuItemDiscountReport.setActionCommand("DiscountReport");
        jMenu5.add(MenuItemDiscountReport);
        jMenu5.add(jSeparator19);

        MenuItemComplimentaryReport.setText("Complimentary Report");
        MenuItemComplimentaryReport.setActionCommand("ComplimentaryReport");
        MenuItemComplimentaryReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemComplimentaryReportActionPerformed(evt);
            }
        });
        jMenu5.add(MenuItemComplimentaryReport);
        jMenu5.add(jSeparator20);

        MenuItemWaiterServiceReport.setText("Waiter Service Report");
        MenuItemWaiterServiceReport.setActionCommand("WaiterServiceReport");
        jMenu5.add(MenuItemWaiterServiceReport);
        jMenu5.add(jSeparator42);

        MenuItemVoidReport.setText("Void Report");
        MenuItemVoidReport.setActionCommand("VoidReport");
        jMenu5.add(MenuItemVoidReport);
        jMenu5.add(jSeparator35);

        MenuItemMenuList.setText("Menu List");
        MenuItemMenuList.setActionCommand("MenuList");
        jMenu5.add(MenuItemMenuList);
        jMenu5.add(jSeparator48);

        MenuItemWastageReport.setText("Wastage Report");
        MenuItemWastageReport.setActionCommand("WastageReport");
        jMenu5.add(MenuItemWastageReport);

        jMenuBar2.add(jMenu5);

        jMenu9.setMnemonic('S');
        jMenu9.setText("System Day");

        MenuItemSystemDateConfig.setText("System Date Config");
        MenuItemSystemDateConfig.setActionCommand("SystemDateConfig");
        jMenu9.add(MenuItemSystemDateConfig);
        jMenu9.add(jSeparator37);

        MenuItemSystemDateOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        MenuItemSystemDateOpen.setText("System Day Open");
        MenuItemSystemDateOpen.setActionCommand("SystemDateOpen");
        jMenu9.add(MenuItemSystemDateOpen);
        jMenu9.add(jSeparator38);

        MenuItemSystemDateClose.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F12, 0));
        MenuItemSystemDateClose.setText("System Day Close");
        MenuItemSystemDateClose.setActionCommand("SystemDateClose");
        MenuItemSystemDateClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemSystemDateCloseActionPerformed(evt);
            }
        });
        jMenu9.add(MenuItemSystemDateClose);

        jMenuBar2.add(jMenu9);

        jMenu8.setMnemonic('S');
        jMenu8.setText("System Config");

        MenuItemUserCreditial.setText("User Creditial");
        MenuItemUserCreditial.setActionCommand("UserCreditial");
        MenuItemUserCreditial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemUserCreditialActionPerformed(evt);
            }
        });
        jMenu8.add(MenuItemUserCreditial);
        jMenu8.add(jSeparator34);

        MenuItemMangeUser.setText("Manage User");
        MenuItemMangeUser.setActionCommand("ManageUser");
        jMenu8.add(MenuItemMangeUser);
        jMenu8.add(jSeparator39);

        MenuItemDepartmentSetup.setText("Department Setup");
        MenuItemDepartmentSetup.setActionCommand("DepartmentSetup");
        jMenu8.add(MenuItemDepartmentSetup);

        jMenuBar2.add(jMenu8);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1143, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuItemWaiterSetupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemWaiterSetupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuItemWaiterSetupActionPerformed

    private void MenuItemIssueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemIssueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuItemIssueActionPerformed

    private void MenuItemCustomerSetupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemCustomerSetupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuItemCustomerSetupActionPerformed

    private void btnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPayActionPerformed

    private void btnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReportActionPerformed

    private void btnAboutUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAboutUsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAboutUsActionPerformed

    private void MenuItemTableSetupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemTableSetupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuItemTableSetupActionPerformed

    private void MenuItemPurchaseReturnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemPurchaseReturnReportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuItemPurchaseReturnReportActionPerformed

    private void MenuItemComplimentaryReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemComplimentaryReportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuItemComplimentaryReportActionPerformed

    private void btnDreamsysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDreamsysActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDreamsysActionPerformed

    private void btnTableStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTableStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTableStatusActionPerformed

    private void MenuItemDistributorSetupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemDistributorSetupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuItemDistributorSetupActionPerformed

    private void btnMenuDetailViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuDetailViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMenuDetailViewActionPerformed

    private void MenuItemGroupSetupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemGroupSetupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuItemGroupSetupActionPerformed

    private void MenuItemUserCreditialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemUserCreditialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuItemUserCreditialActionPerformed

    private void MenuItemSystemDateCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemSystemDateCloseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuItemSystemDateCloseActionPerformed

    private void MenuItemCenterstoreItemWiseIssueReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemCenterstoreItemWiseIssueReportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuItemCenterstoreItemWiseIssueReportActionPerformed
   public void setCompanyTitle(String name){
       lblCompanyName.setText(name);
   }
   public String getCompanyTitle(){
       return lblCompanyName.getText().toString();
   }
   public void setCompanyAddress(String add){
       lblAddress.setText(add);
   }
   public void setCompanyPhone(String phone){
       lblPhoneNumber.setText(phone);
   }
   public String getCompanyAddress(){
       return lblCompanyName.getText().toString();
   }
   public String getCompanyPhone(){
       return lblPhoneNumber.getText().toString();
   }
   public void setUserId(int userid){
       UserId = userid;
   }
   public int getUserId(){
       return UserId;
   }
   public void setLblDate(String st){
       lblDate.setText(st);
   }
   public String getLblDate(){
       return lblDate.getText();
   }
    public void loadImage(String imagepath){
//        String path = "src/images/"+imagepath;
//           URL path = getClass().getResource("/images/"+imagepath);
//        System.out.println(getClass().getResource("/images/"+imagepath));
     //   ImageLabel.setIcon(new ImageIcon("images\"+imagepath));
//        File fl =new File(path.toString());
        ImageLabel.setIcon(new ImageIcon("resources/images/"+imagepath));
//        ImageLabel.setIcon(IOImage.);
    }
    public void LoadlblDayStatus(String imagename){
        lblDayStatus.setIcon(new ImageIcon(getClass().getResource("/images/"+imagename)));
    }
   public void setCompany(Object[] st){
       setCompanyTitle(st[0].toString());
       setCompanyAddress(st[1].toString());
       setCompanyPhone(st[2].toString());
//       loadImage(st[3]);
       if(st[4] == null){
        ImageLabel.setIcon(null);
       }
       else{
       ImageLabel.setIcon(new ImageIcon((byte[])st[4]));
       }
       //add the name of the  company in the title of the jframe alse
//       String frametitle = getTitle();
       String frametitle = "DreamSYS Point Of Sale";
       setTitle(st[0].toString()+"-"+frametitle);
   }
    public void addCompanySetupListener(ActionListener ListenForCompanySetup){
        MenuItemCompanySetup.addActionListener(ListenForCompanySetup);
    }
    public void addCustomerSetupListener(ActionListener Listen){
        MenuItemCustomerSetup.addActionListener(Listen);
    }
    public void addDistributorSetupListener(ActionListener Listen){
        MenuItemDistributorSetup.addActionListener(Listen);
    }
    public void addWaiterSetupListener(ActionListener Listen){
        MenuItemWaiterSetup.addActionListener(Listen);
    }
    public void addSoftwareRegistration(ActionListener Listen){
        MenuItemRegistration.addActionListener(Listen);
    }
    public void addUnitSetupListener(ActionListener Listen){
        MenuItemUnitSetup.addActionListener(Listen);
    }
    public void addGroupSetupListener(ActionListener Listen){
        MenuItemGroupSetup.addActionListener(Listen);
    }
    
    public void addItemEntryListener(ActionListener Listen){
        MenuItemEntry.addActionListener(Listen);
    }
    public void addItemLotListener(ActionListener Listen){
        MenuItemItemLot.addActionListener(Listen);
    }
    //terminal setup
    public void addIssueListener(ActionListener Listner){
        MenuItemIssue.addActionListener(Listner);
    }
    public void addIssueReturnListener(ActionListener Listen){
        MenuItemIssueReturn.addActionListener(Listen);
    }
    public void addPurchaseReturnListener(ActionListener Listen){
        MenuitemPurchaseReturn.addActionListener(Listen);
    }
    public void addMenuEntryListener(ActionListener Listen){
        MenuItemMenuEntry.addActionListener(Listen);
    }
    public void addTableSetupListener(ActionListener Listen){
        MenuItemTableSetup.addActionListener(Listen);
    }
    public void addThresholdSetupListener(ActionListener Listen){
        MenuItemThresholdSetup.addActionListener(Listen);
    }
    public void addComplimentaryReasonSetupListenr(ActionListener Listen){
        MenuItemComplimentaryReasonSetup.addActionListener(Listen);
    }
    /*
    terminal
    */
    public void addOrderListener(ActionListener Listen){
        MenuItemOrder.addActionListener(Listen);
        btnOrder.addActionListener(Listen);
    }
    
    public void addPayListener(ActionListener Listen){
        MenuItemPay.addActionListener(Listen);
        btnPay.addActionListener(Listen);
    }
     public void addDirectBillPayListener(ActionListener Listen){
        MenuItemDirectBillPay.addActionListener(Listen);
//        btnPay.addActionListener(Listen);
    }
    public void addTableStatusListener(ActionListener Listen){
        MenuItemTableStatus.addActionListener(Listen);
        btnTableStatus.addActionListener(Listen);
    }
    public void addVOidBillListener(ActionListener Listen){
        MenuItemVoidBill.addActionListener(Listen);
    }
    public void addWastageListener(ActionListener Listen){
        MenuItemWastage.addActionListener(Listen);
    }
    public void addCreditPaymentListener(ActionListener Listen){
        MenuItemCreditPayment.addActionListener(Listen);
    }
    
    /*
     * centerstore report
     */
    public void addItemReportListener(ActionListener Listen){
        MenuItemItemReport.addActionListener(Listen);
    }
    public void addPurchaseReportListener(ActionListener Listen){
        MenuItemPurchaseReport.addActionListener(Listen);
    }
    public void addPurchaseReturnReportListener(ActionListener Listen){
        MenuItemPurchaseReturnReport.addActionListener(Listen);
    }
    public void addCenterstoreItemwiseIssueReportListener(ActionListener Listen){
        MenuItemCenterstoreItemWiseIssueReport.addActionListener(Listen);
    }
    public void addCenterstoreCategorywiseIssueReportListener(ActionListener Listen){
     MenuItemCenterstoreCategoryIssueReport.addActionListener(Listen);
    }
//    public void addIssueReturnReportlistener(ActionListener Listen){
//        MenuItemIssueReturnReport.addActionListener(Listen);
//    }
    public void addDistributorReportListener(ActionListener Listen){
        MenuItemDistributorReport.addActionListener(Listen);
    }
    /*
     * terminal report
     */
    public void addMenuListListener(ActionListener Listen){
        MenuItemMenuList.addActionListener(Listen);
    }
    public void addSalesReportListener(ActionListener Listen){
        PopUpMenuItemSalesReport.addActionListener(Listen);
        MenuItemSalesReport.addActionListener(Listen);
    }
    public void addIssueStockReportListener(ActionListener Listene){
        MenuItemIssueStockReport.addActionListener(Listene);
        PopUpMenuItemIssueStockReport.addActionListener(Listene);
        
    }
    public void addItemWiseSaleReportListener(ActionListener listen){
        PopUPMenuItemItemWiseSalesReport.addActionListener(listen);
        MenuItemItemWiseSalesReport.addActionListener(listen);
    }
    public void addRecievableReportListener(ActionListener Listen){
        MenuItemReceivableReport.addActionListener(Listen);
    }
    public void addTerminalItemWiseIssueReportListener(ActionListener Listen){
        PopUpMenuItemIssueReport.addActionListener(Listen);
        TerminalMenuItemIssueReport.addActionListener(Listen);
    }
     public void addTerminalCategoryWiseIssueReportListener(ActionListener Listen){
//        PopUpMenuItemIssueReport.addActionListener(Listen);
        TerminalMenuCategoryIssueReport.addActionListener(Listen);
    }
    public void addMenuViewListener(ActionListener Listen){
        MenuItemMenuView.addActionListener(Listen);
    }
    public void addMenuDetailViewListener(ActionListener Listen){
        MenuItemDetailView.addActionListener(Listen);
        btnMenuDetailView.addActionListener(Listen);
        
    }
    
    public void addUserCreditialListener(ActionListener Listen){
        MenuItemUserCreditial.addActionListener(Listen);
    }
    public void addDepartmentSetupListeener(ActionListener listen){
        MenuItemDepartmentSetup.addActionListener(listen);
    }
//    public void addTerminalIssueReturnReportListener(ActionListener listen){
//        TerminalMenuItemIssueReturnReport.addActionListener(listen);
//    }
    public void addSVCReportListener(ActionListener Listen){
        MenuItemSVCReport.addActionListener(Listen);
    }
    public void addVATReportListener(ActionListener Listen){
        MenuItemVATReport.addActionListener(Listen);
    }
    public void addDiscountReportListener(ActionListener Listen){
        MenuItemDiscountReport.addActionListener(Listen);
    }
    public void addComplimentaryReportListener(ActionListener Listen){
        MenuItemComplimentaryReport.addActionListener(Listen);
    }
    public void addWaiterServiceReportListener(ActionListener Listen){
        MenuItemWaiterServiceReport.addActionListener(Listen);
    }
    public void addWastageReportListener(ActionListener Listen){
        MenuItemWastageReport.addActionListener(Listen);
    }
    public void addMouseAdapter(MouseAdapter Listen){
        btnReport.addMouseListener(Listen);
    }
    public void addDreamsysListener(ActionListener Listene){
        btnDreamsys.addActionListener(Listene);
    }
    public void addVoidReportListener(ActionListener Listene){
        MenuItemVoidReport.addActionListener(Listene);
    }
    //system date
    public void addSystemDate(ActionListener Listene){
        MenuItemSystemDateConfig.addActionListener(Listene);
        MenuItemSystemDateOpen.addActionListener(Listene);
        MenuItemSystemDateClose.addActionListener(Listene);
    }
    public void AddToPopUpMenu(){
        ReportPopUpMenu.add(PopUpMenuItemIssueStockReport);
        ReportPopUpMenu.add(PopUpMenuItemSalesReport);
        ReportPopUpMenu.add(PopUPMenuItemItemWiseSalesReport);
        ReportPopUpMenu.add(PopUpMenuItemIssueReport);
        
    }
    
    public void addPopUpMenuListener(MouseAdapter Listen){
        btnReport.addMouseListener(Listen);
    }
    public void addAboutUsListener(ActionListener Listen){
     btnAboutUs.addActionListener(Listen);
    }
    public void incrementCountForPay(){
        countforpay++;
    }
    public int getCountForPay(){
        return countforpay;
    }
    public void setCountForPay(int i){
        countforpay = i;
    }
     public void incrementCountForOrder(){
        countfororder++;
    }
    public int getCountForOrder(){
        return countfororder;
    }
    public void setCountForOrder(int i){
        countfororder = i;
    }
      public void incrementCountForTableStatus(){
        countfortablestatus++;
    }
    public int getCountForTableStatus(){
        return countfortablestatus;
    }
    public void setCountForTableStatus(int i){
        countfortablestatus = i;
    }
     public void incrementCountForDirectPay(){
        countfordirectpay++;
    }
    public int getCountForDirectPay(){
        return countfordirectpay;
    }
    public void setCountForDirectPay(int i){
        countfordirectpay = i;
    }
    public ArrayList getAllMenuItemText(){
//        ArrayList<String> MenuItemText = new ArrayList<>();
        ArrayList<JMenu> MenuList = new ArrayList<>();
           for (Component component : jMenuBar2.getComponents()) {
        JMenu menu = (JMenu)component;
//        System.out.println(menu.getText());
        MenuList.add(menu);
//        System.out.println(menu.getText());
//        for(Component MenuItem:menu.get){
////            if()
//           JMenuItem menuitem = (JMenuItem)MenuItem;
//            System.out.println(menuitem.getText());
        }
           
      return MenuList;
    }
   
    public ArrayList getAllToolBar(){
//        ArrayList<JButton> ToolBarList = new ArrayList<>();
         ArrayList<Component> ToolBarList = new ArrayList<>();
         ToolBarList.addAll(Arrays.asList(jToolBar1.getComponents()));
        return ToolBarList;
    }
    /*
     * this is for internal frame in mainframe
     */
    public void setDesktopPane(){
        desktop = new JDesktopPane();
//        setContentPane(desktop);
          //Make dragging a little faster but perhaps uglier.
       desktop.setDragMode(JDesktopPane.OUTLINE_DRAG_MODE);
    }
    public void addInternalFrame(JInternalFrame frame){
        desktop.add(frame);
    }
    public void addMakeTableStatusImMobile(){
        
    }
    public void addLogOutListener(ActionListener Listen){
        btnLogOut.addActionListener(Listen);
    }
    public void addchangePasswordListener(ActionListener Listen){
        btnChangePassword.addActionListener(Listen);
    }
    public void addManageUserListener(ActionListener Listen){
        MenuItemMangeUser.addActionListener(Listen);
    }
    public void setUserName(String st){
        lblusername.setText(st);
    }
    public String getUserName(){
        return lblusername.getText();
    }
    public void setLogOutVisibleTrue(){
        btnLogOut.setVisible(true);
    }
    public void setLogOutVisibleFalse(){
        btnLogOut.setVisible(false);
    }
    
    public void setChangePasswordVisible(boolean bl){
        btnChangePassword.setVisible(bl);
    }
    public void StartClock(){
        
        Thread Clock = new Thread(){
          @Override
          public void run(){
              int i=0;
              while(i==0){
//                  System.out.println("wala");
                  Calendar cald = new GregorianCalendar();
                  DateFormat df = new SimpleDateFormat("hh:mm:ss a");
//                  int Hour = cald.get(Calendar.HOUR);
//                  int Minutes = cald.get(Calendar.MINUTE);
//                  int Second = cald.get(Calendar.SECOND);
//                  int AMPM =cald.get(Calendar.AM_PM);
//                  int day = cald.get(Calendar.DAY_OF_WEEK);
//                  String stram = AMPM == 0?"am":"pm";
//              String txtclock = Hour+":"+Minutes+":"+Second+" "+stram;
              lblClock.setText(df.format(cald.getTime()));
//              lblClock.setText(txtclock);
              }
          }  
        };
        Clock.start();
    }
   
   
    /**
     * @param args the command line arguments
     */
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImageLabel;
    private javax.swing.JMenuItem MenuItemCenterstoreCategoryIssueReport;
    private javax.swing.JMenuItem MenuItemCenterstoreItemWiseIssueReport;
    private javax.swing.JMenuItem MenuItemCompanySetup;
    private javax.swing.JMenuItem MenuItemComplimentaryReasonSetup;
    private javax.swing.JMenuItem MenuItemComplimentaryReport;
    private javax.swing.JMenuItem MenuItemCreditPayment;
    private javax.swing.JMenuItem MenuItemCustomerSetup;
    private javax.swing.JMenuItem MenuItemDepartmentSetup;
    private javax.swing.JMenuItem MenuItemDetailView;
    private javax.swing.JMenuItem MenuItemDirectBillPay;
    private javax.swing.JMenuItem MenuItemDiscountReport;
    private javax.swing.JMenuItem MenuItemDistributorReport;
    private javax.swing.JMenuItem MenuItemDistributorSetup;
    private javax.swing.JMenuItem MenuItemEntry;
    private javax.swing.JMenuItem MenuItemGroupSetup;
    private javax.swing.JMenuItem MenuItemIssue;
    private javax.swing.JMenuItem MenuItemIssueReturn;
    private javax.swing.JMenuItem MenuItemIssueStockReport;
    private javax.swing.JMenuItem MenuItemItemLot;
    private javax.swing.JMenuItem MenuItemItemReport;
    private javax.swing.JMenuItem MenuItemItemWiseSalesReport;
    private javax.swing.JMenuItem MenuItemMangeUser;
    private javax.swing.JMenuItem MenuItemMenuEntry;
    private javax.swing.JMenuItem MenuItemMenuList;
    private javax.swing.JMenuItem MenuItemMenuView;
    private javax.swing.JMenuItem MenuItemOrder;
    private javax.swing.JMenuItem MenuItemPay;
    private javax.swing.JMenuItem MenuItemPurchaseReport;
    private javax.swing.JMenuItem MenuItemPurchaseReturnReport;
    private javax.swing.JMenuItem MenuItemReceivableReport;
    private javax.swing.JMenuItem MenuItemRegistration;
    private javax.swing.JMenuItem MenuItemSVCReport;
    private javax.swing.JMenuItem MenuItemSalesReport;
    private javax.swing.JMenuItem MenuItemSystemDateClose;
    private javax.swing.JMenuItem MenuItemSystemDateConfig;
    private javax.swing.JMenuItem MenuItemSystemDateOpen;
    private javax.swing.JMenuItem MenuItemTableSetup;
    private javax.swing.JMenuItem MenuItemTableStatus;
    private javax.swing.JMenuItem MenuItemThresholdSetup;
    private javax.swing.JMenuItem MenuItemUnitSetup;
    private javax.swing.JMenuItem MenuItemUserCreditial;
    private javax.swing.JMenuItem MenuItemVATReport;
    private javax.swing.JMenuItem MenuItemVoidBill;
    private javax.swing.JMenuItem MenuItemVoidReport;
    private javax.swing.JMenuItem MenuItemWaiterServiceReport;
    private javax.swing.JMenuItem MenuItemWaiterSetup;
    private javax.swing.JMenuItem MenuItemWastage;
    private javax.swing.JMenuItem MenuItemWastageReport;
    private javax.swing.JMenuItem MenuitemPurchaseReturn;
    public javax.swing.JPopupMenu ReportPopUpMenu;
    private javax.swing.JMenuItem TerminalMenuCategoryIssueReport;
    private javax.swing.JMenuItem TerminalMenuItemIssueReport;
    private javax.swing.JButton btnAboutUs;
    private javax.swing.JButton btnChangePassword;
    private javax.swing.JButton btnDreamsys;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnMenuDetailView;
    private javax.swing.JButton btnOrder;
    private javax.swing.JButton btnPay;
    private javax.swing.JButton btnReport;
    private javax.swing.JButton btnTableStatus;
    private javax.swing.JMenu centerstore;
    public javax.swing.JDesktopPane desktop;
    public javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JToolBar.Separator jSeparator11;
    private javax.swing.JToolBar.Separator jSeparator12;
    private javax.swing.JPopupMenu.Separator jSeparator13;
    private javax.swing.JPopupMenu.Separator jSeparator14;
    private javax.swing.JPopupMenu.Separator jSeparator15;
    private javax.swing.JPopupMenu.Separator jSeparator16;
    private javax.swing.JPopupMenu.Separator jSeparator17;
    private javax.swing.JPopupMenu.Separator jSeparator18;
    private javax.swing.JPopupMenu.Separator jSeparator19;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator20;
    private javax.swing.JPopupMenu.Separator jSeparator21;
    private javax.swing.JPopupMenu.Separator jSeparator22;
    private javax.swing.JPopupMenu.Separator jSeparator23;
    private javax.swing.JPopupMenu.Separator jSeparator24;
    private javax.swing.JToolBar.Separator jSeparator25;
    private javax.swing.JToolBar.Separator jSeparator26;
    private javax.swing.JPopupMenu.Separator jSeparator27;
    private javax.swing.JPopupMenu.Separator jSeparator28;
    private javax.swing.JToolBar.Separator jSeparator29;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator30;
    private javax.swing.JPopupMenu.Separator jSeparator31;
    private javax.swing.JPopupMenu.Separator jSeparator32;
    private javax.swing.JToolBar.Separator jSeparator33;
    private javax.swing.JPopupMenu.Separator jSeparator34;
    private javax.swing.JPopupMenu.Separator jSeparator35;
    private javax.swing.JPopupMenu.Separator jSeparator36;
    private javax.swing.JPopupMenu.Separator jSeparator37;
    private javax.swing.JPopupMenu.Separator jSeparator38;
    private javax.swing.JPopupMenu.Separator jSeparator39;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator40;
    private javax.swing.JPopupMenu.Separator jSeparator41;
    private javax.swing.JPopupMenu.Separator jSeparator42;
    private javax.swing.JPopupMenu.Separator jSeparator43;
    private javax.swing.JPopupMenu.Separator jSeparator44;
    private javax.swing.JPopupMenu.Separator jSeparator45;
    private javax.swing.JSeparator jSeparator46;
    private javax.swing.JPopupMenu.Separator jSeparator47;
    private javax.swing.JPopupMenu.Separator jSeparator48;
    private javax.swing.JPopupMenu.Separator jSeparator49;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblClock;
    private javax.swing.JLabel lblCompanyName;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDayStatus;
    private javax.swing.JLabel lblPhoneNumber;
    private javax.swing.JLabel lblusername;
    // End of variables declaration//GEN-END:variables
}
