/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package report;

import java.awt.BorderLayout;
import java.util.Locale;
import java.util.ResourceBundle;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JRSaveContributor;
import net.sf.jasperreports.view.JRViewer;
import net.sf.jasperreports.view.save.JRDocxSaveContributor;
import net.sf.jasperreports.view.save.JRMultipleSheetsXlsSaveContributor;
import net.sf.jasperreports.view.save.JRPdfSaveContributor;
import net.sf.jasperreports.view.save.JRSingleSheetXlsSaveContributor;

/**
 *
 * @author MinamRosh
 */
public class ReportView extends javax.swing.JFrame {

    /**
     * Creates new form ReportView
     */
    //holds jasper report data
    JasperPrint jPrint;
    //used for displaying the the window
    JRViewer jView;
    Locale locale; // = jView.getLocale();
    ResourceBundle resourceBundle; // = ResourceBundle.getBundle("net/sf/jasperreports/view/viewer", locale);
    JRPdfSaveContributor pdf; // = new JRPdfSaveContributor(locale,resourceBundle);
    JRSingleSheetXlsSaveContributor xls; // = new JRSingleSheetXlsSaveContributor(locale, resourceBundle);
    JRMultipleSheetsXlsSaveContributor xlsx; // = new JRMultipleSheetsXlsSaveContributor(locale, resourceBundle);
    JRDocxSaveContributor doc; // = new JRDocxSaveContributor(locale, resourceBundle);
    
    public ReportView(JasperPrint p, String title) {
        jPrint = p;
        jView = new JRViewer(jPrint);
        jView.setSize(900,700);
        //get the locale;
        
/*      JRPdfSaveContributor pdf = new JRPdfSaveContributor(Locale.ENGLISH, null);
//        JRSingleSheetXlsSaveContributor xls = new JRSingleSheetXlsSaveContributor(Locale.ENGLISH, null);
//        JRMultipleSheetsXlsSaveContributor xlsx = new JRMultipleSheetsXlsSaveContributor(Locale.ENGLISH, null);
    */
        //sets file type extension for saving/exporting report
        setFileTypes();
        this.setTitle(title);
        this.add(jView,BorderLayout.CENTER);
        //this.pack();
        //this.validate();
//this.add(reportPanel);
        initComponents();
        
        
        
        //this.pack();
        setExtendedState(MAXIMIZED_BOTH);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setVisible(true);
        
    }
    
    private void setFileTypes(){
        locale = jView.getLocale();
        resourceBundle = ResourceBundle.getBundle("net/sf/jasperreports/view/viewer", locale);
         pdf = new JRPdfSaveContributor(locale,resourceBundle);
         xls = new JRSingleSheetXlsSaveContributor(locale, resourceBundle);
         xlsx = new JRMultipleSheetsXlsSaveContributor(locale, resourceBundle);
        doc = new JRDocxSaveContributor(locale, resourceBundle);
        jView.setSaveContributors(new JRSaveContributor[]{pdf,xls,xlsx,doc});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Report Viewer");
        setPreferredSize(new java.awt.Dimension(900, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

         //Create and display the form 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new ReportView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
