/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package resturant.orderbill;

import java.awt.KeyEventDispatcher;
import java.awt.KeyboardFocusManager;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemListener;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.AbstractAction;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import javax.swing.ListSelectionModel;
import javax.swing.event.DocumentListener;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import reusableClass.Function;
import reusableClass.Validator;

/**
 *
 * @author SUSHIL
 */
public class OrderBillView extends javax.swing.JInternalFrame {
    
    private final ListSelectionModel ListSelectionModelBillInfo;
    private final ListSelectionModel ListSelectionModelOrderedInfo;
     private final ListSelectionModel ListSelectionModelAddOrderInfo;
      private final ListSelectionModel ListSelectionModelComplimentaryInfo;
    private int CustomerId ;
    private int OrderId;
    private int MainOrderId = 0;
    private int MainBillId = 0;
    private int DepartmentId = 0;
    private Double TotalAfterDiscount = 0.0;
    private int ComplimentaryId  = 0;
   
    private int TableId = 0;
    public ArrayList<String> OrderArray = new ArrayList<>();
    public ArrayList<String[]> ComplimentaryList = new ArrayList<>();
    private KeyboardFocusManager orderbillkeyboardManager;
    
    
    

    /**
     * Creates new form OrderBillView
     */
    public OrderBillView() {
          super("Order Bill Pay Window",false,true,false,true);
//          setDefaultCloseOperation(EXIT_ON_CLOSE);
          
        initComponents();
//        addInternalFrameListener(null)
      
        ListSelectionModelBillInfo = tblBillInfo.getSelectionModel();
        ListSelectionModelBillInfo.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        ListSelectionModelOrderedInfo = tblOrderedList.getSelectionModel();
        ListSelectionModelOrderedInfo.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
         ListSelectionModelAddOrderInfo = tblAddOrder.getSelectionModel();
        ListSelectionModelAddOrderInfo.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        ListSelectionModelComplimentaryInfo = tblComplimentarySelect.getSelectionModel();
        ListSelectionModelComplimentaryInfo.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        setButtonForEnter(btnSave);
        setButtonForEnter(btnCancel);
        setButtonForEnter(btnBillSave);
        setButtonForEnter(btnBillSaveAndPrint);
        setButtonForEnter(btnBillCancel);
       
        //SetFocusListener(txtDiscountAmount);
        //setting all the jformatted texfield into decimal type
//        Validator.DecimalMaker(txtDiscountAmount);
//        Validator.DecimalMaker(txtSVCAmount);
//        Validator.DecimalMaker(txtSVCPercent);
//        Validator.DecimalMaker(txtAmountReturn);
        Validator.DecimalMaker(txtTenderedAmount);
        Validator.DecimalMaker(txtDiscountAmount);
       
        Validator.PercentageMaker(txtVATPercent);
        txtDiscountPercent.addFocusListener(new Function.SetJFormattedTextFieldFocusListener(txtDiscountPercent));
       // txtReturnAmount.addFocusListener(new SetFocusListener(txtReturnAmount));
        txtSVCPercent.addFocusListener(new Function.SetJFormattedTextFieldFocusListener(txtSVCPercent));
        txtSearch.addFocusListener(new Function.SetTextFieldFocusListener(txtSearch));
        txtTenderedAmount.addFocusListener(new Function.SetTextFieldFocusListener(txtTenderedAmount));
        orderbillkeyboardManager = KeyboardFocusManager.getCurrentKeyboardFocusManager();
//     
        /*
         * center in the middle of the screen
         */
        JDialogBillPayment.setLocationRelativeTo(null);
        /*
         * for adding textwinadmdos
         */
        txtTenderedAmount.addActionListener(new addEnterFocusListener());
        //this button is not needed
        btnBillSaveAndPrint.setVisible(false);
        /*
         * adding clos listener
         */
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JDialogBillPayment = new javax.swing.JDialog();
        btnBillSave = new javax.swing.JButton();
        btnBillSaveAndPrint = new javax.swing.JButton();
        btnBillCancel = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        comboBoxCustomerName = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        checkBoxComplimentary = new javax.swing.JCheckBox();
        radioCash = new javax.swing.JRadioButton();
        radioCredit = new javax.swing.JRadioButton();
        btnAddCustomer = new javax.swing.JButton();
        comboboxComplimentaryName = new javax.swing.JComboBox();
        buttonGroupPaymentType = new javax.swing.ButtonGroup();
        JDialogAddOrder = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblAddOrder = new javax.swing.JTable();
        JDialogComplimentary = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblComplimentarySelect = new javax.swing.JTable();
        lblBillNo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBillInfo = new javax.swing.JTable();
        lblAmountReturn = new javax.swing.JLabel();
        btnAddOrder = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        txtTotal = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        checkBoxSVCByPercentage = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTenderedAmount = new javax.swing.JFormattedTextField();
        txtGrandTotal1 = new javax.swing.JFormattedTextField();
        txtSubTotalAmount = new javax.swing.JFormattedTextField();
        checkBoxDiscountByPercentage = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        checkBoxVATByPercentage = new javax.swing.JCheckBox();
        txtDiscountPercent = new javax.swing.JFormattedTextField();
        txtSVCPercent = new javax.swing.JFormattedTextField();
        txtVATPercent = new javax.swing.JFormattedTextField();
        //NumberFormatter numberformatter = new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00;(#,##0.00)"));
        //NumberFormatter numberformatter = new javax.swing.text.NumberFormatter(NumberFormat.getCurrencyInstance(Locale.US));
        //NumberFormatter numberformatter = new javax.swing.text.NumberFormatter(DecimalFormat.getInstance());
        //NumberFormat format = DecimalFormat.getInstance();
        //format.setMinimumFractionDigits(2);
        //                format.setMaximumFractionDigits(2);
        // InternationalFormatter numberformatter = new InternationalFormatter(format);
        //numberformatter.setAllowsInvalid(false);
        //numberformatter.setCommitsOnValidEdit(true);
        //numberformatter.setOverwriteMode(true);
        txtSVCAmount = new javax.swing.JFormattedTextField();
        txtDiscountAmount = new javax.swing.JFormattedTextField();
        txtVATAmount = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        txtAmountReturn = new javax.swing.JFormattedTextField();
        btnSearchOrder = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        btnRefresh = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblOrderedList = new javax.swing.JTable();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        txtGrandTotal2 = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        comboDepartmentName = new javax.swing.JComboBox();

        JDialogBillPayment.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        JDialogBillPayment.setMinimumSize(new java.awt.Dimension(500, 300));
        JDialogBillPayment.setModal(true);
        JDialogBillPayment.setResizable(false);

        btnBillSave.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBillSave.setMnemonic('s');
        btnBillSave.setText("Save");
        btnBillSave.setToolTipText("ALT+S");
        btnBillSave.setActionCommand("BillSave");

        btnBillSaveAndPrint.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBillSaveAndPrint.setText("Save&Print");
        btnBillSaveAndPrint.setActionCommand("BillSaveAndPrint");

        btnBillCancel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBillCancel.setMnemonic('c');
        btnBillCancel.setText("Cancel");
        btnBillCancel.setToolTipText("ALT+C");
        btnBillCancel.setActionCommand("BillCancel");

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        comboBoxCustomerName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comboBoxCustomerName.setActionCommand("comboCustomerName");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Customer:");

        checkBoxComplimentary.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        checkBoxComplimentary.setMnemonic('o');
        checkBoxComplimentary.setText("Complimentary");
        checkBoxComplimentary.setToolTipText("ALT+O");
        checkBoxComplimentary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxComplimentaryActionPerformed(evt);
            }
        });

        buttonGroupPaymentType.add(radioCash);
        radioCash.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        radioCash.setMnemonic('a');
        radioCash.setSelected(true);
        radioCash.setText("Cash");
        radioCash.setToolTipText("ALT+A");

        buttonGroupPaymentType.add(radioCredit);
        radioCredit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        radioCredit.setMnemonic('R');
        radioCredit.setText("Credit");
        radioCredit.setToolTipText("ALT+R");
        radioCredit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioCreditActionPerformed(evt);
            }
        });

        btnAddCustomer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAddCustomer.setMnemonic('U');
        btnAddCustomer.setText("ADD Customer");
        btnAddCustomer.setToolTipText("ALT+U");
        btnAddCustomer.setActionCommand("ADDCustomer");
        btnAddCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCustomerActionPerformed(evt);
            }
        });

        comboboxComplimentaryName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comboboxComplimentaryName.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(radioCash)
                .addGap(62, 62, 62)
                .addComponent(radioCredit)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(checkBoxComplimentary)
                        .addGap(18, 18, 18)
                        .addComponent(comboboxComplimentaryName, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(comboBoxCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAddCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioCash)
                    .addComponent(radioCredit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(comboBoxCustomerName)
                        .addComponent(btnAddCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkBoxComplimentary, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboboxComplimentaryName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {comboBoxCustomerName, jLabel4});

        javax.swing.GroupLayout JDialogBillPaymentLayout = new javax.swing.GroupLayout(JDialogBillPayment.getContentPane());
        JDialogBillPayment.getContentPane().setLayout(JDialogBillPaymentLayout);
        JDialogBillPaymentLayout.setHorizontalGroup(
            JDialogBillPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JDialogBillPaymentLayout.createSequentialGroup()
                .addGroup(JDialogBillPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JDialogBillPaymentLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(btnBillSave, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBillSaveAndPrint)
                        .addGap(21, 21, 21)
                        .addComponent(btnBillCancel))
                    .addGroup(JDialogBillPaymentLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        JDialogBillPaymentLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnBillCancel, btnBillSave, btnBillSaveAndPrint});

        JDialogBillPaymentLayout.setVerticalGroup(
            JDialogBillPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JDialogBillPaymentLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(JDialogBillPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBillSave, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBillSaveAndPrint)
                    .addComponent(btnBillCancel))
                .addGap(34, 34, 34))
        );

        JDialogBillPaymentLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnBillCancel, btnBillSave, btnBillSaveAndPrint});

        JDialogAddOrder.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        JDialogAddOrder.setMinimumSize(new java.awt.Dimension(520, 500));
        JDialogAddOrder.setModalityType(java.awt.Dialog.ModalityType.DOCUMENT_MODAL);
        JDialogAddOrder.setResizable(false);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Add Order"));

        tblAddOrder.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblAddOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblAddOrder.setRowHeight(20);
        tblAddOrder.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(tblAddOrder);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout JDialogAddOrderLayout = new javax.swing.GroupLayout(JDialogAddOrder.getContentPane());
        JDialogAddOrder.getContentPane().setLayout(JDialogAddOrderLayout);
        JDialogAddOrderLayout.setHorizontalGroup(
            JDialogAddOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JDialogAddOrderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JDialogAddOrderLayout.setVerticalGroup(
            JDialogAddOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JDialogAddOrderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JDialogComplimentary.setMinimumSize(new java.awt.Dimension(450, 400));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Complimentary Select Table"));

        tblComplimentarySelect.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(tblComplimentarySelect);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout JDialogComplimentaryLayout = new javax.swing.GroupLayout(JDialogComplimentary.getContentPane());
        JDialogComplimentary.getContentPane().setLayout(JDialogComplimentaryLayout);
        JDialogComplimentaryLayout.setHorizontalGroup(
            JDialogComplimentaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JDialogComplimentaryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JDialogComplimentaryLayout.setVerticalGroup(
            JDialogComplimentaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JDialogComplimentaryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        lblBillNo.setBackground(new java.awt.Color(153, 255, 102));
        lblBillNo.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblBillNo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        lblBillNo.setOpaque(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Bill No:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText(" Grand Total :");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setFocusCycleRoot(true);

        tblBillInfo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblBillInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBillInfo.getTableHeader().setReorderingAllowed(false);
        tblBillInfo.setEnabled(false);
        tblBillInfo.setRowHeight(20);
        jScrollPane1.setViewportView(tblBillInfo);

        btnAddOrder.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAddOrder.setMnemonic('o');
        btnAddOrder.setText("Add Order");
        btnAddOrder.setToolTipText("ALT+O");
        btnAddOrder.setActionCommand("AddOrder");
        btnAddOrder.setEnabled(false);

        txtTotal.setEditable(false);
        txtTotal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        txtTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTotal.setValue(0.0);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Discount:");

        checkBoxSVCByPercentage.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        checkBoxSVCByPercentage.setText("By %");
        checkBoxSVCByPercentage.setActionCommand("SVC");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Amount Tendered:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Total:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("VAT:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("SVC:");

        txtTenderedAmount.setToolTipText("INSERT");
        txtTenderedAmount.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtTenderedAmount.setValue(0.0);

        txtGrandTotal1.setEditable(false);
        txtGrandTotal1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        txtGrandTotal1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtGrandTotal1.setValue(0.0);

        txtSubTotalAmount.setEditable(false);
        txtSubTotalAmount.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        txtSubTotalAmount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSubTotalAmount.setValue(0.0
        );

        checkBoxDiscountByPercentage.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        checkBoxDiscountByPercentage.setText("By %");
        checkBoxDiscountByPercentage.setActionCommand("Discount");
        checkBoxDiscountByPercentage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxDiscountByPercentageActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Sub Total:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Grand Total :");

        checkBoxVATByPercentage.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        checkBoxVATByPercentage.setSelected(true);
        checkBoxVATByPercentage.setText("By %");
        checkBoxVATByPercentage.setActionCommand("VAT");
        checkBoxVATByPercentage.setEnabled(false);

        txtDiscountPercent.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00;(¤#,##0.00)"))));
        txtDiscountPercent.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDiscountPercent.setValue(0.0);
        txtDiscountPercent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiscountPercentActionPerformed(evt);
            }
        });

        txtSVCPercent.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtSVCPercent.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSVCPercent.setValue(0.0);

        txtVATPercent.setEditable(false);
        txtVATPercent.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getPercentInstance())));
        txtVATPercent.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtVATPercent.setValue(0.0
        );

        txtSVCAmount.setValue(new Double(0.0));
        txtSVCAmount.setEditable(false);
        txtSVCAmount.setBackground(new java.awt.Color(153, 153, 153));
        txtSVCAmount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtDiscountAmount.setEditable(false);
        txtDiscountAmount.setValue(0.0);
        txtDiscountAmount.setBackground(new java.awt.Color(153, 153, 153));
        txtDiscountAmount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtVATAmount.setEditable(false);
        txtVATAmount.setBackground(new java.awt.Color(153, 153, 153));
        txtVATAmount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addGap(23, 23, 23)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(checkBoxSVCByPercentage, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkBoxDiscountByPercentage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDiscountPercent, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                            .addComponent(txtSVCPercent))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDiscountAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSVCAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(checkBoxVATByPercentage, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTotal)
                            .addComponent(txtSubTotalAmount, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtGrandTotal1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTenderedAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(txtVATPercent, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtVATAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDiscountPercent, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDiscountAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(checkBoxSVCByPercentage)
                                .addComponent(jLabel5))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtSVCPercent, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSVCAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(4, 4, 4))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(checkBoxDiscountByPercentage)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSubTotalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtVATAmount, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtVATPercent, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(checkBoxVATByPercentage)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGrandTotal1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenderedAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel6Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel3, jLabel5, jLabel6});

        jPanel6Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel10, jLabel11, jLabel8});

        jPanel6Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtDiscountAmount, txtSVCAmount});

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Amount Return:");

        txtAmountReturn.setEditable(false);
        txtAmountReturn.setForeground(new java.awt.Color(255, 0, 0));
        txtAmountReturn.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        txtAmountReturn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtAmountReturn.setValue(0.0);
        txtAmountReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAmountReturnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(btnAddOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(95, 95, 95))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(122, 122, 122)
                                .addComponent(lblAmountReturn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(txtAmountReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)))
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addGap(10, 10, 10))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(btnAddOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtAmountReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)))
                .addComponent(lblAmountReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnSearchOrder.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSearchOrder.setMnemonic('e');
        btnSearchOrder.setText("Search");
        btnSearchOrder.setToolTipText("ALT+E");
        btnSearchOrder.setActionCommand("OrderSearch");

        txtSearch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnRefresh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRefresh.setMnemonic('r');
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Ordered  Table List"));

        tblOrderedList.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblOrderedList.getTableHeader().setReorderingAllowed(false);
        tblOrderedList.setToolTipText("HOME");
        tblOrderedList.setRowHeight(20);
        jScrollPane2.setViewportView(tblOrderedList);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        btnSave.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSave.setMnemonic('s');
        btnSave.setText("Save");
        btnSave.setToolTipText("ALT+S");
        btnSave.setEnabled(false);

        btnCancel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCancel.setMnemonic('c');
        btnCancel.setText("Cancel");
        btnCancel.setToolTipText("ALT+C");

        txtGrandTotal2.setEditable(false);
        txtGrandTotal2.setBackground(new java.awt.Color(153, 255, 102));
        txtGrandTotal2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txtGrandTotal2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        txtGrandTotal2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtGrandTotal2.setValue(0.0);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Department Name:");

        comboDepartmentName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comboDepartmentName.setActionCommand("comboDepartmentName");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                                .addComponent(btnCancel)
                                .addGap(19, 19, 19))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(comboDepartmentName, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblBillNo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtGrandTotal2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSearchOrder)
                .addGap(79, 79, 79)
                .addComponent(btnRefresh))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCancel, btnSave});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSearchOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btnRefresh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblBillNo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtGrandTotal2, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCancel)
                            .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboDepartmentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCancel, btnSave});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {comboDepartmentName, jLabel9});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void checkBoxComplimentaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxComplimentaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxComplimentaryActionPerformed

    private void radioCreditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioCreditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioCreditActionPerformed

    private void txtDiscountPercentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiscountPercentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiscountPercentActionPerformed

    private void checkBoxDiscountByPercentageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxDiscountByPercentageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxDiscountByPercentageActionPerformed

    private void btnAddCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCustomerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddCustomerActionPerformed

    private void txtAmountReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAmountReturnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAmountReturnActionPerformed
//        public void setSVCPercentage(Double d){
//            SVCpercentage = d;
//        }
//        public Double getSVCPercentage(){
//            return SVCpercentage;
//        }
//         public void setVATPercentage(Double d){
//            VATPercentage = d;
//        }
//        public Double getVATPercentage(){
//            return VATPercentage;
//        }
         //this is when discount percantage is chlick
//        public void setDiscountAmount(Double d){
//            DiscountAmount = d;
//        }
//        public Double getDiscountAmount(){
//            return DiscountAmount;
//        }
        
        public String getBillId(){
             return lblBillNo.getText();
        }
        public void setBillId(String id){
            lblBillNo.setText(id);
        }
          public void setMainBillId(int i){
            MainBillId = i;
        }
        public int getMainBillId(){
            return MainBillId;
        }
         public Double getVAT(){
             return ((Number)txtVATPercent.getValue()).doubleValue();
        }
        public void setVAT(Double id){
            txtVATPercent.setValue(id);
        }
//         public String getDate(){
//             return lblDate.getText();
//        }
//        public void setDate(String id){
//            lblDate.setText(id);
//        }
         public int getCustomerId(){
             return CustomerId;
        }
        public void setCustomerId(int id){
            CustomerId = id;
        }
           public int getOrderId(){
             return OrderId;
        }
        public void setOrderId(int id){
            OrderId = id;
        }
          public int getMainOrderId(){
             return MainOrderId;
        }
        public void setMainOrderId(int id){
            MainOrderId = id;
        }
               public int getDepartmentId(){
        return DepartmentId;
    }
    public void setDepartmentId(int id){
        DepartmentId = id;
    }
        public Double getGrandTotal1(){
            return ((Number)txtGrandTotal1.getValue()).doubleValue();
        }
        public void setGrandTotal1(Double total){
            txtGrandTotal1.setValue(total);
        }
        public Double getGrandTotal2(){
            return ((Number)txtGrandTotal2.getValue()).doubleValue();
        }
        public void setGrandTotal2(Double total){
            txtGrandTotal2.setValue(total);
        }
        public void setTotal(Double total){
            txtTotal.setValue(total);
        }
        public Double getTotal(){
             return (Double)txtTotal.getValue();
        }
        public void setTotalAfterDiscount(Double ds){
            TotalAfterDiscount = ds;
        }
        public Double getTotalAfterDiscount(){
            return TotalAfterDiscount;
        }
        public void setSVC(Double svc){
            txtSVCPercent.setValue(svc.doubleValue());
        }
        public Double getSVC(){
            return ((Number)txtSVCPercent.getValue()).doubleValue();
        }
          public void setSearch(String svc){
            txtSearch.setText(svc);
        }
        public String getSearch(){
            return txtSearch.getText().trim();
        }
        public void setSubTotal(double amount){
            txtSubTotalAmount.setValue(new Double(amount));
        }
        public double getSubTotal(){
            return ((Number)txtSubTotalAmount.getValue()).doubleValue();
        }
        public void setDiscount(Double dsc){
            txtDiscountPercent.setValue(dsc);
        }
        public Double getDiscount(){
            return ((Number)txtDiscountPercent.getValue()).doubleValue();
        }
        public void setTenderedAmount(Double amt){
            txtTenderedAmount.setValue(amt);
        }
        public Double getTenderedAmount(){
            return ((Number)txtTenderedAmount.getValue()).doubleValue();
        }
        public void setChangeAmount(Double amt){
           txtAmountReturn.setValue(amt);
        }
        public Double getChangeAmount(){
            return ((Number)txtAmountReturn.getValue()).doubleValue();
        }
        //added code
        public double getSVCAmount(){
            return ((Number)txtSVCAmount.getValue()).doubleValue();
        }
        public void setSVCAmount(double db){
            txtSVCAmount.setValue(new Double(db));
        }
        public void settextSVCAmount(String db){
            txtSVCAmount.setText(db);
        }
        public double getDiscountAmount(){
            return ((Number)txtDiscountAmount.getValue()).doubleValue();
        }
        public void setDiscountAmount(double ui){
           txtDiscountAmount.setValue(ui);
        }
        public void settextDiscountAmount(String db){
            txtDiscountAmount.setText(db);
        }
        public void setVATAmount(double db){
            txtVATAmount.setValue(new Double(db));
        }
        public double getVATAmount(){
             return ((Number)txtVATAmount.getValue()).doubleValue();
        }
        public void setTableId(int i){
            TableId = i;
        }
        public int getTableId(){
            return TableId;
        }
      
        public void setComplimentary(Boolean flag){
          //  if(flag == true){
                checkBoxComplimentary.setSelected(flag);
          //  }
        }
        public Boolean getBooleanDiscountPercentage(){
        return checkBoxDiscountByPercentage.isSelected();
        }
        public void  setBooleanDiscountPercentage(Boolean flag){
            checkBoxDiscountByPercentage.setSelected(flag);
        }
          public Boolean getBooleanSVCPercentage(){
        return checkBoxSVCByPercentage.isSelected();
        }
        public void  setBooleanSVCPercentage(Boolean flag){
            checkBoxSVCByPercentage.setSelected(flag);
        }
        public Boolean getPaymentType(){
        return radioCash.isSelected();
        }
         public Boolean getBooleanComplimentaryType(){
        return checkBoxComplimentary.isSelected();
        }
        public void setPaymentTypeForCash(Boolean flag){
            radioCash.setSelected(flag);
        }
        public void setPaymentTypeForCredit(Boolean flag){
            radioCredit.setSelected(flag);
           
        }
        public void setComboComplimentaryName(Object[] data){
            DefaultComboBoxModel model = new DefaultComboBoxModel(data);
            comboboxComplimentaryName.setModel(model);
        }
        public void setComboComplimentaryName(String reason){
            comboboxComplimentaryName.setSelectedItem(reason);
        }
        public String getComboComplimentaryName(){
            return comboboxComplimentaryName.getSelectedItem().toString();
        }
        public  JComboBox returnComboComplimentaryName(){
            return comboboxComplimentaryName;
        }
        public void setComboComplimentaryEnable(boolean bl){
            comboboxComplimentaryName.setEnabled(bl);
            
        }
        public void setComplimentaryId(int id){
            ComplimentaryId = id;
        }
        public int getComplimentaryId(){
            return ComplimentaryId;
        }
        public void setComboCustomerName(String[] name){
            DefaultComboBoxModel model = new DefaultComboBoxModel(name);
            comboBoxCustomerName.setModel(model);
        }
        public void setComboCustomerName(String name){
            comboBoxCustomerName.setSelectedItem(name);
        }
        public String getcomboCustomerName(){
            return comboBoxCustomerName.getSelectedItem().toString();
        }
           public void setcomboDepartmentName(Object[] data){
        DefaultComboBoxModel model = new DefaultComboBoxModel(data);
        comboDepartmentName.setModel(model);
    }
    public void setcomboDepartmentName(String st){
        
        comboDepartmentName.setSelectedItem(st);
       
    }
    public String getcomboDepartmentName(){
        return comboDepartmentName.getSelectedItem().toString();
    }
    public JComboBox returnComboDepartmentName(){
        return comboDepartmentName;
    }
        public void  refreshJTableOrderedList(DefaultTableModel model){
            tblOrderedList.setModel(model);
        }
        public void refreshJTableBillInfo(DefaultTableModel model){
            tblBillInfo.setModel(model);
        }
        public void refreshJTableAddOrder(DefaultTableModel model){
            tblAddOrder.setModel(model);
        }
         public void refreshJTableComplimentarySelect(DefaultTableModel model){
            tblComplimentarySelect.setModel(model);
        }
       
       
      
        public DefaultTableModel gettblOrderList(){
            return (DefaultTableModel)tblOrderedList.getModel();
        }
        public DefaultTableModel gettblBillInfo(){
            return (DefaultTableModel) tblBillInfo.getModel();
        }
          public DefaultTableModel gettblAddOrder(){
            return (DefaultTableModel) tblAddOrder.getModel();
        }
        public DefaultTableModel gettblComplimentarySelect(){
        return (DefaultTableModel) tblComplimentarySelect.getModel();
         }
          public void setSaveEditableTrue(){
            btnSave.setEnabled(true);
        }
        public void setSaveEditableFalse(){
            btnSave.setEnabled(false);
        }
        public void setCancelEditableTrue(){
            btnCancel.setEnabled(true);
        }
        public void setCancelEditableFalse(){
            btnCancel.setEnabled(false);
        }
        public void setBillSaveEditableFalse(){
            btnBillSave.setEnabled(false);
        }
        public void setBillSaveEditableTrue(){
            btnBillSave.setEnabled(true);
        }
        public void setBillCancelEditableFalse(){
            btnBillCancel.setEnabled(false);
        }
        public void setBillCancelEditableTrue(){
            btnBillCancel.setEnabled(true);
        }
        public void setBillSaveAndPrintEditableFalse(){
            btnBillSaveAndPrint.setEnabled(false);
        }
        public void setBillSaveAndPrintEditableTrue(){
            btnBillSaveAndPrint.setEnabled(true);
        }
          public void setAddOrderEditableTrue(){
            btnAddOrder.setEnabled(true);
        }
        public void setAddOrderEditableFalse(){
            btnAddOrder.setEnabled(false);
        }
        public void setCheckBoxComplimentaryTrue(){
            checkBoxComplimentary.setSelected(true);
        }
        public void setCheckBoxComplimentaryFalse(){
            checkBoxComplimentary.setSelected(false);
        }
         public void setCheckBoxSVCTrue(){
            checkBoxSVCByPercentage.setSelected(true);
        }
        public void setCheckBoxSVCFalse(){
            checkBoxSVCByPercentage.setSelected(false);
        }
        public void setSVCCheck(boolean bl){
            checkBoxSVCByPercentage.setSelected(bl);
        }
        public void setDiscountCheck(boolean bl){
            checkBoxDiscountByPercentage.setSelected(bl);
        }
         public void setCheckBoxDiscountTrue(){
            checkBoxDiscountByPercentage.setSelected(true);
        }
        public void setCheckBoxDiscountFalse(){
            checkBoxDiscountByPercentage.setSelected(false);
        }
        public void addSaveListener(ActionListener ListenForSave){
            btnSave.addActionListener(ListenForSave);
        }
        public void addCancelListener(ActionListener ListenForCancel){
            btnCancel.addActionListener(ListenForCancel);
        }
        public void addBillSaveListener(ActionListener ListenForSave){
            btnBillSave.addActionListener(ListenForSave);
        }
        public void addBillSaveAndPrintListener(ActionListener ListenForSave){
            btnBillSaveAndPrint.addActionListener(ListenForSave);
        }
        public void addBillCancelListener(ActionListener ListenForCancel){
            btnBillCancel.addActionListener(ListenForCancel);
        }
        public void addListSelectionListenerForOrderedList(ListSelectionListener ListenForSelect){
            ListSelectionModelOrderedInfo.addListSelectionListener(ListenForSelect);
        }
        public void addRefreshListener(ActionListener ListenForreresh){
            btnRefresh.addActionListener(ListenForreresh);
        }
          public void addSearchListener(ActionListener ListenForreresh){
            btnSearchOrder.addActionListener(ListenForreresh);
        }
          public void addTextSearchListener(ActionListener ListenForSearch){
             txtSearch.addActionListener(ListenForSearch);
          }
        public void addComboClickCustomerNameActionListener(ActionListener ListenForClick){
            comboBoxCustomerName.addActionListener(ListenForClick);
        }
        public void addComboDepartmentNameListener(ActionListener Listen){
            comboDepartmentName.addActionListener(Listen);
        }
        public void addComboComplimentaryReason(ActionListener Listen){
            comboboxComplimentaryName.addActionListener(Listen);
        }
          public void addAddOrderListener(ActionListener ListenForreresh){
            btnAddOrder.addActionListener(ListenForreresh);
        }
          public void addCheckBoxComplimentaryListener(ActionListener ListenForClick){
              checkBoxComplimentary.addActionListener(ListenForClick);
          }
          public void addCheckBoxComplimentaryItemListener(ItemListener ListenForSelect){
              checkBoxComplimentary.addItemListener(ListenForSelect);
          }
          //adding  documetlistener
          public void addSVCDocumentListener(DocumentListener Listen){
              txtSVCPercent.getDocument().addDocumentListener(Listen);
          }
          public  void addDiscountDocumentListener(DocumentListener Listen){
              txtDiscountPercent.getDocument().addDocumentListener(Listen);
          }
          public void addTenderedAmountDocumentListener(DocumentListener Listen){
              txtTenderedAmount.getDocument().addDocumentListener(Listen);
          }
          public void addTotalDocumentListener(DocumentListener Listen){
              txtTotal.getDocument().addDocumentListener(Listen);
          }
          public void addGrandTotalDocumentListener(DocumentListener Listen){
              txtGrandTotal1.getDocument().addDocumentListener(Listen);
          }
          //adding enter on the tenderamount
          public void addTenderedAmountActionListener(ActionListener listen){
              txtTenderedAmount.addActionListener(listen);
          }
          //returning textfield
          public JFormattedTextField returnSVC(){
              return txtSVCPercent;
          }
          public JFormattedTextField returnDiscount(){
              return txtDiscountPercent;
          }
          public JFormattedTextField returnTenderedAmount(){
              return txtTenderedAmount;
          }
          
         
          public void addCheckDiscountListener(ItemListener listen){
              checkBoxDiscountByPercentage.addItemListener(listen);
          }
//          public void addCheckDiscountListener(ActionListener listen){
//              checkBoxDiscountByPercentage.addActionListener(listen);
//          }
          public void addCheckSVCListener(ItemListener listen){
              checkBoxSVCByPercentage.addItemListener(listen);
          }
//          public void addWindowListener(WindowAdapter ListenForClose){
//              
//          }
           /*
         * listenr for enter in table for add order
         */
        public void addDoubliClickListenerForAddOrder(MouseAdapter ListenForDoubleclick){
            tblAddOrder.addMouseListener(ListenForDoubleclick);
        }
        public void addDoubliClickListenerForComplimentarySelect(MouseAdapter ListenForDoubleclick){
            tblComplimentarySelect.addMouseListener(ListenForDoubleclick);
        }
        
        public final void setButtonForEnter(JButton jb){
         jb.registerKeyboardAction(jb.getActionForKeyStroke(
                                      KeyStroke.getKeyStroke(KeyEvent.VK_SPACE, 0, false)),
                                      KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0, false),
                                      JComponent.WHEN_FOCUSED);
 
        jb.registerKeyboardAction(jb.getActionForKeyStroke(
                                      KeyStroke.getKeyStroke(KeyEvent.VK_SPACE, 0, true)),
                                      KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0, true),
                                      JComponent.WHEN_FOCUSED);
        
    }
        public void addItemListenerForCashCredit(ItemListener ListenForChange){
            radioCash.addItemListener(ListenForChange);
            radioCredit.addItemListener(ListenForChange);
        }
        public void addAbstractActionListener(AbstractAction action){
            txtTenderedAmount.getInputMap().put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER,0), "Listen");
            txtTenderedAmount.getActionMap().put("Listen", action);
            
            
        }
        public class addEnterFocusListener implements ActionListener{

        @Override
        public void actionPerformed(ActionEvent e) {
           // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//       JFormattedTextField jf = (JFormattedTextField)e.getSource();
      // System.out.println("walaoutside");
           
               JOptionPane.showMessageDialog(null,"wala");
                btnSave.requestFocusInWindow();
            
        }
            
    
        }
     

       public Double[] getBillRate(){
          Double[] data = new Double[8];
         // data[0] = getBillId();
          data[0] = getTotal();
          if(getBooleanSVCPercentage()){
//            System.out.println(getSVCAmount());
          data[1] = getSVCAmount();
          }
          else{
          data[1] = getSVC();
//           System.out.println(getSVC());
          }
          
          data[2] = getVATAmount();
          data[3 ]= getSubTotal();
          if(getBooleanDiscountPercentage()){
          data[4] = getDiscountAmount();
//          System.out.println(getDiscountAmount());
          }
          else{
           data[4] = getDiscount();
//           System.out.println(getDiscount());
          }
        
          data[5] = getGrandTotal1();
         // data[6] = getOrderId();
          data[6] = getTenderedAmount();
          data[7] = getChangeAmount();
          return data;
      }
      public String[] getBillOtherInfo(){
          String[] data =new String[7];
          data[0] = getBillId();
          data[1] = String.valueOf(getBooleanSVCPercentage());
          data[2] = String.valueOf(getBooleanDiscountPercentage());
          data[3] = String.valueOf(getCustomerId());
          data[4] = String.valueOf(getPaymentType());
          data[5] = String.valueOf(getBooleanComplimentaryType());
          data[6] = String.valueOf(getComplimentaryId());
//          data[7] = getDepartmentId();
          
          return data;
      }
      public void setOrderBill(){
          
      }
      public void clearOrderBill(){
          initComboCustomerName();
          setBillId("0");
          setTotal(0.0);
          setSVC(0.0);
          setVAT(0.0);
          setSVCAmount(0.0);
          setDiscountAmount(0.0);
          setVATAmount(0.0);
          setCustomerId(0);
          setDiscount(0.0);
          setOrderId(0);
          setTenderedAmount(0.0);
          setChangeAmount(0.0);
          setSearch("");
//          setDiscountAmount(0.0);
          ComplimentaryList.clear();
          setCheckBoxComplimentaryFalse();
          setCheckBoxDiscountFalse();
          setComplimentaryId(0);
          
          comboboxComplimentaryName.setSelectedIndex(0);
//          setCheckBoxDiscountFalse();
          
          
      }
       public void AddSelectInCombo(JComboBox jc){
      jc.insertItemAt("SELECT", 0);
      jc.setSelectedIndex(0);
    }
         public void addCustomerWindow(ActionListener Listen){
            btnAddCustomer.addActionListener(Listen);
        }
       public JComboBox returnComboBoxCustomer(){
           return comboBoxCustomerName;
       }
       public void initComboCustomerName(){
           comboBoxCustomerName.setSelectedIndex(0);
       }
      public void requestFocusOnTenderedAmount(){
         txtTenderedAmount.requestFocus();
      }
       public void requestFocusOnButtonBillSave(){
         btnBillSave.requestFocus();
      }
        public void requestFocusOnButtonSimpleBillSave(){
         btnSave.requestFocus();
      }

    //retriving all the getter of jbuuton
    public JButton getBtnAddCustomer() {
        return btnAddCustomer;
    }

    public JButton getBtnAddOrder() {
        return btnAddOrder;
    }

    public JButton getBtnBillCancel() {
        return btnBillCancel;
    }

    public JButton getBtnBillSave() {
        return btnBillSave;
    }

    public JButton getBtnBillSaveAndPrint() {
        return btnBillSaveAndPrint;
    }

    public JButton getBtnCancel() {
        return btnCancel;
    }

    public JButton getBtnRefresh() {
        return btnRefresh;
    }

        public JButton getBtnSave() {
        return btnSave;
    }

    public JButton getBtnSearchOrder() {
        return btnSearchOrder;
    }
        
        public void addShortcutForOrderBill(KeyEventDispatcher listen){
            orderbillkeyboardManager.addKeyEventDispatcher(listen);
        }
    
    

     
         
         
         //return parameters for printing bill after payment
         public Map getBillParam(){
             @SuppressWarnings("Convert2Diamond")
             Map param = new HashMap<Object, Object>();
             try{
                
             //putting parameter 
             param.put("billNo",lblBillNo.getText().trim());
             param.put("total",getTotal().toString());
             param.put("svc", getSVC().toString());
             param.put("vat", getVAT().toString());
             param.put("subtotal",String.valueOf(getSubTotal()));
             param.put("discount",getDiscount().toString());
             param.put("grandtotal",getGrandTotal1().toString());
             param.put("amountTen",getTenderedAmount().toString());
             param.put("amountRetn",getChangeAmount().toString());
             param.put("terminal", 1);
             param.put("orderId",getOrderId());
             
             }catch(ExceptionInInitializerError e){
                 JOptionPane.showMessageDialog(this,"resturant.orderbill.orderbillview"+e);
             }
             return param;
         }
    /*  public class BillPropertyChangeListener implements PropertyChangeListener{

        @Override
        public void propertyChange(PropertyChangeEvent evt) {
          //  throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        Object  name = evt.getSource();
        //System.out.println(name);
          if(txtSVC == name){
             
              setSubTotal(getTotal()+(getSVC()*getSVCPercentage())+(getVAT()*getVATPercentage()));
            
          }
          if(txtDiscountAmount == name){
              if(getBooleanDiscountPercentage()){
                  Double value = (getDiscount()*getSubTotal())/100;
                  setDiscount(value);
                  System.out.println("wala");
              }
          }
      }
      }
       */ 
           

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderBillView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderBillView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderBillView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderBillView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new OrderBillView().setVisible(true);
//            }
//        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JDialog JDialogAddOrder;
    public javax.swing.JDialog JDialogBillPayment;
    public javax.swing.JDialog JDialogComplimentary;
    private javax.swing.JButton btnAddCustomer;
    private javax.swing.JButton btnAddOrder;
    private javax.swing.JButton btnBillCancel;
    public javax.swing.JButton btnBillSave;
    private javax.swing.JButton btnBillSaveAndPrint;
    private javax.swing.JButton btnCancel;
    public javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSave;
    public javax.swing.JButton btnSearchOrder;
    private javax.swing.ButtonGroup buttonGroupPaymentType;
    private javax.swing.JCheckBox checkBoxComplimentary;
    private javax.swing.JCheckBox checkBoxDiscountByPercentage;
    private javax.swing.JCheckBox checkBoxSVCByPercentage;
    private javax.swing.JCheckBox checkBoxVATByPercentage;
    private javax.swing.JComboBox comboBoxCustomerName;
    private javax.swing.JComboBox comboDepartmentName;
    private javax.swing.JComboBox comboboxComplimentaryName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblAmountReturn;
    private javax.swing.JLabel lblBillNo;
    public javax.swing.JRadioButton radioCash;
    public javax.swing.JRadioButton radioCredit;
    public javax.swing.JTable tblAddOrder;
    public javax.swing.JTable tblBillInfo;
    public javax.swing.JTable tblComplimentarySelect;
    public javax.swing.JTable tblOrderedList;
    private javax.swing.JFormattedTextField txtAmountReturn;
    private javax.swing.JFormattedTextField txtDiscountAmount;
    private javax.swing.JFormattedTextField txtDiscountPercent;
    private javax.swing.JFormattedTextField txtGrandTotal1;
    private javax.swing.JFormattedTextField txtGrandTotal2;
    private javax.swing.JFormattedTextField txtSVCAmount;
    private javax.swing.JFormattedTextField txtSVCPercent;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JFormattedTextField txtSubTotalAmount;
    private javax.swing.JFormattedTextField txtTenderedAmount;
    private javax.swing.JFormattedTextField txtTotal;
    private javax.swing.JFormattedTextField txtVATAmount;
    private javax.swing.JFormattedTextField txtVATPercent;
    // End of variables declaration//GEN-END:variables
}
