/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package companysetup;

import java.awt.Color;
import java.awt.event.ActionListener;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.awt.event.ItemListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.WindowAdapter;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JTextField;
import javax.swing.KeyStroke;
import javax.swing.text.InternationalFormatter;
import reusableClass.Function;
import reusableClass.Validator;

/**
 *
 * @author SUSHIL
 */
public class CompanySetupView extends javax.swing.JDialog {
     private String ImagePath = "" ;
    private BufferedImage  buffImage = null;
    private File file = null;
   

    /**
     * Creates new form CompanySetupView
     */
    public CompanySetupView(JFrame parent,boolean modal) {
        
        super(parent,modal);
        
        initComponents();
      
       // btnSave.setVisible(false);
       // btnCancel.setVisible(false);
//        panelCompany.setVisible(false);
        setButtonForEnter(btnSave);
        setButtonForEnter(btnCancel);
        setButtonForEnter(btnRegister);
        setButtonForEnter(btnView);
        setButtonForEnter(btnUpdate);
        setButtonForEnter(btnChargeCancel);
        setButtonForEnter(btnChargeEdit);
        setButtonForEnter(btnChargeSave);
        setButtonForEnter(btnChargeSetup);
        txtAddress.addFocusListener(new  Function.SetTextFieldFocusListener(txtAddress));
        
        txtBillGreet.addFocusListener(new Function.SetTextFieldFocusListener(txtBillGreet));
        txtCompanyName.addFocusListener(new Function.SetTextFieldFocusListener(txtCompanyName));
        txtEmail.addFocusListener(new Function.SetTextFieldFocusListener(txtEmail));
        txtFax.addFocusListener(new Function.SetTextFieldFocusListener(txtFax));
        txtPanNo.addFocusListener(new Function.SetJFormattedTextFieldFocusListener(txtPanNo));
        txtPhone.addFocusListener(new Function.SetJFormattedTextFieldFocusListener(txtPhone));
        txtWebsite.addFocusListener(new Function.SetTextFieldFocusListener(txtWebsite));
        txtSVC.addFocusListener(new Function.SetTextFieldFocusListener(txtSVC));
        txtCompanySlogan.addFocusListener(new Function.SetTextFieldFocusListener(txtCompanySlogan));
        Validator.PercentageMaker(txtSVC);
        Validator.PercentageMaker(txtVAT);
         /*
         * centering the frame
         */
        setLocationRelativeTo(null);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JDailogChargeSetup = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtSVC = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        radioVATInclude = new javax.swing.JRadioButton();
        radioVATNotInclude = new javax.swing.JRadioButton();
        txtVAT = new javax.swing.JFormattedTextField();
        btnChargeSave = new javax.swing.JButton();
        btnChargeCancel = new javax.swing.JButton();
        btnChargeEdit = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        btnView = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnRegister = new javax.swing.JButton();
        btnChargeSetup = new javax.swing.JButton();
        panelCompany = new javax.swing.JPanel();
        lblPhone = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtFax = new javax.swing.JTextField();
        lblCompanyName = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblFax = new javax.swing.JLabel();
        txtWebsite = new javax.swing.JTextField();
        lblPan = new javax.swing.JLabel();
        lblWebsite = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        txtCompanyName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtBillGreet = new javax.swing.JTextField();
        btnCancel = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        lblCompanyLogo = new javax.swing.JLabel();
        btnUploadImage = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtCompanySlogan = new javax.swing.JTextField();
        txtPanNo = new javax.swing.JFormattedTextField();
        txtPhone = new javax.swing.JFormattedTextField();
        ImageLabel = new javax.swing.JLabel();

        JDailogChargeSetup.setTitle("Tax Setup");
        JDailogChargeSetup.setMinimumSize(new java.awt.Dimension(450, 300));
        JDailogChargeSetup.setModal(true);
        JDailogChargeSetup.setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Service Charge(%):");

        txtSVC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSVC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSVCActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("VAT(%):");

        buttonGroup1.add(radioVATInclude);
        radioVATInclude.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        radioVATInclude.setText("Include");

        buttonGroup1.add(radioVATNotInclude);
        radioVATNotInclude.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        radioVATNotInclude.setText("Not Include");

        txtVAT.setEnabled(false);

        btnChargeSave.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnChargeSave.setMnemonic('S');
        btnChargeSave.setText("Save");
        btnChargeSave.setActionCommand("ChargeSave");
        btnChargeSave.setEnabled(false);

        btnChargeCancel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnChargeCancel.setMnemonic('C');
        btnChargeCancel.setText("Cancel");
        btnChargeCancel.setActionCommand("ChargeCancel");
        btnChargeCancel.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(btnChargeSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtVAT, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(txtSVC)
                            .addComponent(radioVATInclude))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioVATNotInclude))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnChargeCancel)
                        .addContainerGap())))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnChargeCancel, btnChargeSave});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSVC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioVATInclude)
                    .addComponent(radioVATNotInclude))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtVAT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnChargeSave)
                    .addComponent(btnChargeCancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel3, jLabel5});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtSVC, txtVAT});

        btnChargeEdit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnChargeEdit.setMnemonic('E');
        btnChargeEdit.setText("Edit");
        btnChargeEdit.setActionCommand("ChargeEdit");

        javax.swing.GroupLayout JDailogChargeSetupLayout = new javax.swing.GroupLayout(JDailogChargeSetup.getContentPane());
        JDailogChargeSetup.getContentPane().setLayout(JDailogChargeSetupLayout);
        JDailogChargeSetupLayout.setHorizontalGroup(
            JDailogChargeSetupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JDailogChargeSetupLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnChargeEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        JDailogChargeSetupLayout.setVerticalGroup(
            JDailogChargeSetupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JDailogChargeSetupLayout.createSequentialGroup()
                .addGroup(JDailogChargeSetupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JDailogChargeSetupLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JDailogChargeSetupLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(btnChargeEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Company Setup Form");
        setName("ComapanySetupView"); // NOI18N
        setResizable(false);

        btnView.setMnemonic('V');
        btnView.setText("View");

        btnUpdate.setMnemonic('U');
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnRegister.setMnemonic('R');
        btnRegister.setText("Register");

        btnChargeSetup.setMnemonic('T');
        btnChargeSetup.setText("Tax Setup");
        btnChargeSetup.setActionCommand("TaxSetup");

        panelCompany.setBorder(javax.swing.BorderFactory.createTitledBorder("Company Setup/View"));

        lblPhone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPhone.setText("Phone *");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Email");

        txtEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtFax.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblCompanyName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCompanyName.setText("Company Name *");

        lblAddress.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblAddress.setText("Address *");

        lblFax.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblFax.setText("Fax");

        txtWebsite.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblPan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPan.setText("Pan/Vat *");

        lblWebsite.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblWebsite.setText("Website");

        txtAddress.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtCompanyName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Bill Greet:");

        txtBillGreet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBillGreetActionPerformed(evt);
            }
        });

        btnCancel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCancel.setMnemonic('C');
        btnCancel.setText("Cancel");

        btnSave.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSave.setMnemonic('S');
        btnSave.setText("Save");

        lblCompanyLogo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCompanyLogo.setText("Company Logo:");

        btnUploadImage.setMnemonic('P');
        btnUploadImage.setText("Upload");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Slogan:");

        txtCompanySlogan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCompanySloganActionPerformed(evt);
            }
        });

        txtPanNo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("######"))));
        txtPanNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        try {
            txtPhone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(###) ###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtPhone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCompanyLayout = new javax.swing.GroupLayout(panelCompany);
        panelCompany.setLayout(panelCompanyLayout);
        panelCompanyLayout.setHorizontalGroup(
            panelCompanyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCompanyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCompanyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCompanyLogo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblWebsite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblFax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCompanyName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPhone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPan, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCompanyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCompanySlogan, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtBillGreet)
                    .addGroup(panelCompanyLayout.createSequentialGroup()
                        .addGroup(panelCompanyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFax)
                            .addComponent(txtWebsite)
                            .addComponent(txtEmail)
                            .addComponent(txtCompanyName)
                            .addComponent(txtAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                            .addGroup(panelCompanyLayout.createSequentialGroup()
                                .addGroup(panelCompanyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnUploadImage, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnSave, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                                .addGap(93, 93, 93)
                                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtPanNo)
                            .addComponent(txtPhone))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelCompanyLayout.setVerticalGroup(
            panelCompanyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCompanyLayout.createSequentialGroup()
                .addGroup(panelCompanyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCompanyLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblCompanyName))
                    .addComponent(txtCompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCompanyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddress)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCompanyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhone)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(panelCompanyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFax)
                    .addComponent(txtFax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCompanyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblWebsite)
                    .addComponent(txtWebsite, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCompanyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(panelCompanyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblPan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPanNo))
                .addGap(25, 25, 25)
                .addGroup(panelCompanyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCompanySlogan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCompanyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtBillGreet, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCompanyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCompanyLogo)
                    .addComponent(btnUploadImage))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(panelCompanyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnCancel))
                .addContainerGap())
        );

        panelCompanyLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel4, lblAddress, lblCompanyName, lblFax, lblPan, lblPhone, lblWebsite, txtAddress, txtCompanyName, txtCompanySlogan, txtEmail, txtFax, txtPhone, txtWebsite});

        ((InternationalFormatter)txtPanNo.getFormatter()).setAllowsInvalid(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRegister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnChargeSetup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 10, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnView)
                        .addGap(13, 13, 13)
                        .addComponent(btnUpdate)
                        .addGap(18, 18, 18)
                        .addComponent(btnChargeSetup)
                        .addGap(18, 18, 18)
                        .addComponent(btnRegister))
                    .addComponent(panelCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txtBillGreetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBillGreetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBillGreetActionPerformed

    private void txtSVCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSVCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSVCActionPerformed

    private void txtCompanySloganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCompanySloganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCompanySloganActionPerformed

    private void txtPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneActionPerformed

    public void setCompanyName(String CompanyName){
       txtCompanyName.setText(CompanyName);
    }
    public String getCompanyName(){
        return txtCompanyName.getText().trim();
    }
    public void setAddress(String Address){
        txtAddress.setText(Address);
    }
    public String getAddress(){
        return txtAddress.getText().trim();
        
    }
    public void SetBillGreet(String City){
        txtBillGreet.setText(City);
    }
    public String getBillGreet(){
        return txtBillGreet.getText().trim();
    }
     public void SetCompanySlogan(String City){
        txtCompanySlogan.setText(City);
    }
    public String getCompanySlogan(){
        return txtCompanySlogan.getText().trim();
    }
    public void setPhone(String Phone){
        txtPhone.setText(Phone);
    }
    public String getPhone(){
        return txtPhone.getText().trim();
    }
    public void setFax(String Fax){
        txtFax.setText(Fax);
    }
    
    public String getFax(){
        return txtFax.getText();
    }
    public void setWebsite(String Website){
        txtWebsite.setText(Website);
    }
    public String getWebsite(){
        return txtWebsite.getText();
    }
    public void setEmail(String Email){
        txtEmail.setText(Email);
        
    }
    public String getEmail(){
        return txtEmail.getText();
    }
//    public void setPan(String Pan){
//        txtPanNo.setText(Pan);
//    }
//    public String getPan(){
//        return txtPanNo.getText();
//    }
     public void setPan(Integer Pan){
        txtPanNo.setValue(new Integer(Pan));
    }
    public Integer getPan(){
        return ((Number)txtPanNo.getValue()).intValue();
    }
    /*
    this is for image
    */
     public void setBufferedImage(BufferedImage buff){
        buffImage = buff;
    }
    public BufferedImage getBufferedImage(){
        return buffImage;
    }
    public File getImageFile(){
        return file;
    }
    public void setImageFile(File fl){
        file = fl;
    }
    public void setImageLabel(ImageIcon img){
        ImageLabel.setIcon(img);
    }
     public void loadImage(String imagepath){
//        String path = ;
     //   ImageLabel.setIcon(new ImageIcon("images\"+imagepath));
        ImageLabel.setIcon(new ImageIcon("resources/images/"+imagepath));
    }
    public ImageIcon getImageLabel(){
        return (ImageIcon) ImageLabel.getIcon();
    }
     public void setImagePath(String mname){
       ImagePath= mname;
    }
    public String getImagePath(){
      return  ImagePath;
    }
    
    public void hideSaveBtn(){
        btnSave.setVisible(false);
    }
    public void showSaveBtn(){
        btnSave.setVisible(true);
    }
    public void hideCancelBtn(){
        btnCancel.setVisible(false);
    }
    public void showCancelBtn(){
        btnCancel.setVisible(true);
    }
    public void showPanelCompany(){
        panelCompany.setVisible(true);
        
    }
    public void showbtnRegister(){
        btnRegister.setVisible(true);
    }
    public void hidebtnRegister(){
        btnRegister.setVisible(false);
    }
    public void clickBtnRegister(){
        btnRegister.doClick();
    }
     public void showbtnView(){
        btnView.setVisible(true);
    }
    public void hidebtnView(){
        btnView.setVisible(false);
    }
      public void showbtnUpdate(){
        btnUpdate.setVisible(true);
    }
    public void hidebtnUpdate(){
        btnUpdate.setVisible(false);
    }
      public void showbtnChargeSetup(){
        btnChargeSetup.setVisible(true);
    }
    public void hidebtnChargeSetup(){
        btnChargeSetup.setVisible(false);
    }
    public void showlblCompanyLogo(){
        lblCompanyLogo.setVisible(true);
    }
    public void hidelblCompanyLogo(){
        lblCompanyLogo.setVisible(false);
    }
     public void showbtnCompanyLogo(){
        btnUploadImage.setVisible(true);
    }
    public void hidebtnCompanyLogo(){
        btnUploadImage.setVisible(false);
    }
      public void setChargeSaveEditableFalse(){
       btnChargeSave.setEnabled(false);
    }
    public void setChargeSaveEditableTrue(){
       btnChargeSave.setEnabled(true);
    }
      public void setChargeCancelEditableFalse(){
       btnChargeCancel.setEnabled(false);
    }
    public void setChargeCancelEditableTrue(){
       btnChargeCancel.setEnabled(true);
    }
      public void setChargeEditEditableFalse(){
       btnChargeEdit.setEnabled(false);
    }
    public void setChargeEditEditableTrue(){
       btnChargeEdit.setEnabled(true);
    }
       public void setChargeSVCEditableFalse(){
      txtSVC.setEnabled(false);
    }
    public void setChargeSVCEditableTrue(){
       txtSVC.setEnabled(true);
    }
    public void setSVC(Double svc){
        txtSVC.setValue(svc);
    }
    public Double getSVC(){
        return ((Number)txtSVC.getValue()).doubleValue();
    }
    public void setVAT(Double vat){
        txtVAT.setValue(vat);
    }
    public Double getVAT(){
        return ((Number)txtVAT.getValue()).doubleValue();
    }
    public void hidePanelCompany(){
        panelCompany.setVisible(false);
    }
    public void setTxtEditableFalse(){
        txtCompanyName.setEditable(false);
        txtAddress.setEditable(false);
//     txtCity.setEditable(false);
        txtBillGreet.setEditable(false);
        txtPhone.setEditable(false);
        txtFax.setEditable(false);
        txtWebsite.setEditable(false);
        txtEmail.setEditable(false);
        txtPanNo.setEditable(false);
        txtCompanySlogan.setEditable(false);
    }
    public void setTxtEditableTrue(){
        txtCompanyName.setEditable(true);
        txtAddress.setEditable(true);
   //     txtCity.setEditable(true);
        txtBillGreet.setEditable(true);
        txtPhone.setEditable(true);
        txtFax.setEditable(true);
        txtWebsite.setEditable(true);
        txtEmail.setEditable(true);
        txtPanNo.setEditable(true);
        txtCompanySlogan.setEditable(true);
    }
    void addViewListener(ActionListener ListenForView){
        btnView.addActionListener(ListenForView);
    }
    void addViewKeyListener(KeyListener ListenForView){
        btnView.addKeyListener(ListenForView);
    }
    void addUpdateListener(ActionListener ListenForUpdate){
        btnUpdate.addActionListener(ListenForUpdate);
    }
    void addUpdateKeyListener(KeyListener ListenForUpdate){
        btnUpdate.addKeyListener(ListenForUpdate);
    }
    void addRegisterListener(ActionListener ListenForEntry){
        btnRegister.addActionListener(ListenForEntry);
        
    }
    void addRegisterKeyListener(KeyListener ListenForEntry){
        btnRegister.addKeyListener(ListenForEntry);
    }
    void addSaveListener(ActionListener ListenForSave){
        btnSave.addActionListener(ListenForSave);
    }
    void addSaveKeyListener(KeyListener ListenForSave){
        btnSave.addKeyListener(ListenForSave);
    }
    void addCancelListener(ActionListener ListenForCancel){
        btnCancel.addActionListener(ListenForCancel);
    }
    void addCancelKeyListener(KeyListener ListenForCancel){
        btnCancel.addKeyListener(ListenForCancel);
        
    }
    void addChargeEditListener(ActionListener ListenForEdit){
        btnChargeEdit.addActionListener(ListenForEdit);
    }
    void addChargeSaveListener(ActionListener ListenForSave){
        btnChargeSave.addActionListener(ListenForSave);
    }
    void addChargeCancelListener(ActionListener ListenForCancel){
        btnChargeCancel.addActionListener(ListenForCancel);
    }
    void addChargeSetupListener(ActionListener ListenForSetup){
        btnChargeSetup.addActionListener(ListenForSetup);
    }
    void addVATIncludeListener(ItemListener ListenForInclude){
        radioVATInclude.addItemListener(ListenForInclude);
    }
    void addVATNotIncludeListener(ItemListener ListenForNotInclude){
        radioVATNotInclude.addItemListener(ListenForNotInclude);
    }
     public void addImageUploadListener(ActionListener ListenForUpload){
        btnUploadImage.addActionListener(ListenForUpload);
    }
     public void addWindowCloseListener(WindowAdapter listen){
        this.addWindowListener(listen);
     }
    void setradioVATIncludeCheckedTrue(){
        radioVATInclude.setSelected(true);
    }
    void setradioVATIncludeCheckedFalse(){
        radioVATInclude.setSelected(false);
    }
    void setradioVATNotIncludeCheckedTrue(){
        radioVATNotInclude.setSelected(true);
    }
    void setradioVATNotIncludeCheckedFalse(){
        radioVATNotInclude.setSelected(false);
    }
    public final class SetFocusListener implements FocusListener{
      JTextField jf;
        public SetFocusListener(JTextField field){
         jf = field;   
        }

        @Override
        public void focusGained(FocusEvent e) {
         //   throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
          jf.setBackground(new Color(136,249,168));
          jf.selectAll();
        }

        @Override
        public void focusLost(FocusEvent e) {
        //    throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
       jf.setBackground(Color.white);
        }
        
    }
      public final void setButtonForEnter(JButton jb){
         jb.registerKeyboardAction(jb.getActionForKeyStroke(
                                      KeyStroke.getKeyStroke(KeyEvent.VK_SPACE, 0, false)),
                                      KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0, false),
                                      JComponent.WHEN_FOCUSED);
 
        jb.registerKeyboardAction(jb.getActionForKeyStroke(
                                      KeyStroke.getKeyStroke(KeyEvent.VK_SPACE, 0, true)),
                                      KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0, true),
                                      JComponent.WHEN_FOCUSED);
        
    }
    
    
    /**
     * @param args the command line arguments
     */
      public static void main(String[] arg){
          new CompanySetupView(null, true).setVisible(true);
      }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel ImageLabel;
    public javax.swing.JDialog JDailogChargeSetup;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnChargeCancel;
    private javax.swing.JButton btnChargeEdit;
    private javax.swing.JButton btnChargeSave;
    private javax.swing.JButton btnChargeSetup;
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnUploadImage;
    public javax.swing.JButton btnView;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblCompanyLogo;
    private javax.swing.JLabel lblCompanyName;
    private javax.swing.JLabel lblFax;
    private javax.swing.JLabel lblPan;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblWebsite;
    private javax.swing.JPanel panelCompany;
    private javax.swing.JRadioButton radioVATInclude;
    private javax.swing.JRadioButton radioVATNotInclude;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtBillGreet;
    private javax.swing.JTextField txtCompanyName;
    private javax.swing.JTextField txtCompanySlogan;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFax;
    private javax.swing.JFormattedTextField txtPanNo;
    private javax.swing.JFormattedTextField txtPhone;
    public javax.swing.JFormattedTextField txtSVC;
    private javax.swing.JFormattedTextField txtVAT;
    private javax.swing.JTextField txtWebsite;
    // End of variables declaration//GEN-END:variables
}
