/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package resturant.order;

import java.awt.KeyEventDispatcher;
import java.awt.KeyboardFocusManager;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemListener;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.WindowListener;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.util.HashMap;
import java.util.Map;
import javax.swing.AbstractAction;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JFormattedTextField;
import javax.swing.JTextField;
import javax.swing.KeyStroke;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import reusableClass.Function;
import reusableClass.Validator;

/**
 *
 * @author SUSHIL
 */
public  class OrderView extends javax.swing.JInternalFrame {
private int  TableId = 0;
private int MainOrderId = 0;
private int MenuId;
private int WaiterId;
private int CustomerId;
private int UnitId ;
private int DepartmentId=0;
private String ItemBaseUnit = new String();
private Double DoubleSVC = new Double(0.0);
private Double DoubleVAT = new Double(0.0);

private BigDecimal rate;
private BigDecimal TotalAmount;
private final ListSelectionModel selectionModelOrderTable;
private final ListSelectionModel selectionModelOrderedTable;
//this for listening the  keyboard key throug out the frame
private KeyboardFocusManager kfmanager;
    /**
     * Creates new formOrderView
     */
    public OrderView() {
       super("Order Window",false,true,false,true);
        initComponents();
        
        selectionModelOrderTable = tblOrderList.getSelectionModel();
        selectionModelOrderTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        selectionModelOrderedTable = tblOrderedList.getSelectionModel();
        selectionModelOrderedTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        setButtonForEnter(btnAdd);
        setButtonForEnter(btnDelete);
        setButtonForEnter(btnSearchMenu);
        setButtonForEnter(btnSearchOrder);
        setButtonForEnter(btnOrder);
        setButtonForEnter(btnOrderAndPrint);
        setButtonForEnter(btnOrderEdit);
        setButtonForEnter(btnOrderDelete);
        setButtonForEnter(btnRefresh);
        setButtonForEnter(btnCancelOrder);
        setButtonForEnter(btnAddCustomer);
         setButtonForEnter(btnAddTable);
         setButtonForEnter(btnAddWaiter);
         /*
          * setiing the quantity with jformatted text field
          */
         /*
         checking for enter
         */
         
         
         
         Validator.DecimalMaker(txtOrderQuantity);
         txtOrderQuantity.addFocusListener(new Function.SetJFormattedTextFieldFocusListener(txtOrderQuantity));
         txtSearch.addFocusListener(new Function.SetTextFieldFocusListener(txtSearch));
         txtSearchMenu.addFocusListener(new Function.SetTextFieldFocusListener(txtSearchMenu));
         //getting the key acion
         kfmanager= KeyboardFocusManager.getCurrentKeyboardFocusManager();
         
         
//          setLocationRelativeTo(null);
       /*  DialogBox.addWindowListener(new WindowAdapter(){
             public void windowClosed(WindowEvent se){
                 JOptionPane.showMessageDialog(null, "wala closing");
             }
         });*/
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SearchDailog = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        scroll = new javax.swing.JScrollPane();
        tblSearch = new javax.swing.JTable();
        DialogBox = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        comboMenuName = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        txtOrderQuantity = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        lblOrderId = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtSearchMenu = new javax.swing.JTextField();
        btnSearchMenu = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        comboTableName = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        comboCustomerName = new javax.swing.JComboBox();
        btnAddCustomer = new javax.swing.JButton();
        btnAddTable = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        comboWaiterName = new javax.swing.JComboBox();
        btnAddWaiter = new javax.swing.JButton();
        btnOrder = new javax.swing.JButton();
        btnOrderAndPrint = new javax.swing.JButton();
        btnOrderEdit = new javax.swing.JButton();
        btnOrderDelete = new javax.swing.JButton();
        btnCancelOrder = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblOrderedList = new javax.swing.JTable();
        txtSearch = new javax.swing.JTextField();
        btnSearchOrder = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrderList = new javax.swing.JTable();
        btnDelete = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        comboDepartmentName = new javax.swing.JComboBox();

        SearchDailog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        SearchDailog.setTitle("Search Result");
        SearchDailog.setMinimumSize(new java.awt.Dimension(611, 437));
        SearchDailog.setModal(true);
        SearchDailog.setName("Search Result"); // NOI18N

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Search Result"));

        scroll.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        tblSearch.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scroll.setViewportView(tblSearch);
        tblSearch.getTableHeader().setReorderingAllowed(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout SearchDailogLayout = new javax.swing.GroupLayout(SearchDailog.getContentPane());
        SearchDailog.getContentPane().setLayout(SearchDailogLayout);
        SearchDailogLayout.setHorizontalGroup(
            SearchDailogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchDailogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        SearchDailogLayout.setVerticalGroup(
            SearchDailogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchDailogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        DialogBox.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout DialogBoxLayout = new javax.swing.GroupLayout(DialogBox.getContentPane());
        DialogBox.getContentPane().setLayout(DialogBoxLayout);
        DialogBoxLayout.setHorizontalGroup(
            DialogBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        DialogBoxLayout.setVerticalGroup(
            DialogBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setNextFocusableComponent(comboMenuName);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Item Add"));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Item Name:*");

        comboMenuName.setActionCommand("ComboMenuName");
        comboMenuName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMenuNameActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Quantity:*");

        btnAdd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAdd.setMnemonic('a');
        btnAdd.setText("Add");
        btnAdd.setMinimumSize(new java.awt.Dimension(87, 25));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Order Id:");

        lblOrderId.setBackground(new java.awt.Color(153, 255, 102));
        lblOrderId.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblOrderId.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        lblOrderId.setOpaque(true);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 255));
        jLabel7.setText("Search for the Item to Add");

        txtSearchMenu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSearchMenu.setHighlighter(null);

        btnSearchMenu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSearchMenu.setMnemonic('s');
        btnSearchMenu.setText("Search");
        btnSearchMenu.setActionCommand("SearchMenu");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboMenuName, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(txtOrderQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblOrderId, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSearchMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSearchMenu)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblOrderId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSearchMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSearchMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtOrderQuantity)
                        .addGap(5, 5, 5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(2, 2, 2))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(comboMenuName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Order Table"));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Table Name:");

        comboTableName.setActionCommand("ComboTableName");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Customer Name:");

        comboCustomerName.setActionCommand("ComboCustomerName");

        btnAddCustomer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAddCustomer.setMnemonic('u');
        btnAddCustomer.setText("ADD Customer");
        btnAddCustomer.setActionCommand("ADDCustomer");
        btnAddCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCustomerActionPerformed(evt);
            }
        });

        btnAddTable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAddTable.setMnemonic('t');
        btnAddTable.setText("Add Table");
        btnAddTable.setActionCommand("AddTable");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Waiter Name:");

        comboWaiterName.setActionCommand("ComboWaiterName");

        btnAddWaiter.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAddWaiter.setMnemonic('w');
        btnAddWaiter.setText("ADD Waiter");
        btnAddWaiter.setActionCommand("ADDWaiter");
        btnAddWaiter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddWaiterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboWaiterName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboCustomerName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboTableName, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddTable)
                    .addComponent(btnAddCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddWaiter, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboTableName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddTable))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(btnAddWaiter, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(comboWaiterName)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(7, 7, 7))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAddCustomer, btnAddTable});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {comboCustomerName, comboTableName, comboWaiterName});

        btnOrder.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnOrder.setMnemonic('o');
        btnOrder.setText("Order");
        btnOrder.setEnabled(false);

        btnOrderAndPrint.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnOrderAndPrint.setMnemonic('p');
        btnOrderAndPrint.setText("Order&Print");
        btnOrderAndPrint.setEnabled(false);
        btnOrderAndPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderAndPrintActionPerformed(evt);
            }
        });

        btnOrderEdit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnOrderEdit.setMnemonic('e');
        btnOrderEdit.setText("Edit");
        btnOrderEdit.setActionCommand("OrderEdit");
        btnOrderEdit.setEnabled(false);
        btnOrderEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderEditActionPerformed(evt);
            }
        });

        btnOrderDelete.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnOrderDelete.setMnemonic('d');
        btnOrderDelete.setText("Delete");
        btnOrderDelete.setActionCommand("OrderDelete");
        btnOrderDelete.setEnabled(false);
        btnOrderDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderDeleteActionPerformed(evt);
            }
        });

        btnCancelOrder.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCancelOrder.setMnemonic('c');
        btnCancelOrder.setText("Cancel");
        btnCancelOrder.setActionCommand("OrderCancel");

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Ordered  Table List"));

        tblOrderedList.setAutoCreateRowSorter(true);
        tblOrderedList.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblOrderedList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblOrderedList.getTableHeader().setReorderingAllowed(false);
        tblOrderedList.setRowHeight(20);
        jScrollPane2.setViewportView(tblOrderedList);

        txtSearch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnSearchOrder.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSearchOrder.setMnemonic('h');
        btnSearchOrder.setText("Search");
        btnSearchOrder.setActionCommand("OrderSearch");

        btnRefresh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRefresh.setMnemonic('r');
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearchOrder)
                        .addGap(42, 42, 42)
                        .addComponent(btnRefresh)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Order List"));

        tblOrderList.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblOrderList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblOrderList.setRowHeight(20);
        tblOrderList.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblOrderList);

        btnDelete.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDelete.setMnemonic('l');
        btnDelete.setText("Delete");
        btnDelete.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Department Name:");

        comboDepartmentName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comboDepartmentName.setActionCommand("ComboDepartmentName");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(btnOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnOrderAndPrint)
                        .addGap(18, 18, 18)
                        .addComponent(btnOrderEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnOrderDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboDepartmentName, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnOrder)
                        .addComponent(btnOrderAndPrint)
                        .addComponent(btnOrderEdit)
                        .addComponent(btnOrderDelete)
                        .addComponent(btnCancelOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(comboDepartmentName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCancelOrder, btnOrder, btnOrderAndPrint, btnOrderDelete, btnOrderEdit});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboMenuNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMenuNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboMenuNameActionPerformed

    private void btnAddWaiterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddWaiterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddWaiterActionPerformed

    private void btnOrderEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOrderEditActionPerformed

    private void btnOrderAndPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderAndPrintActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOrderAndPrintActionPerformed

    private void btnOrderDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOrderDeleteActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnAddCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCustomerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddCustomerActionPerformed
    public String getOrderId(){
        return lblOrderId.getText().trim();
    }
    public void setOrderId(String id){
        lblOrderId.setText(id);
    }
     public int getMainOrderId(){
        return MainOrderId;
    }
    public void setMainOrderId(int id){
       MainOrderId = id;
    }
    public BigDecimal getRate(){
        return rate;
    }
    public void setRate(String rate){
        this.rate = new BigDecimal(rate).setScale(2, RoundingMode.HALF_UP);
    }
    public  BigDecimal getTotalAmount(){
        return TotalAmount;
    }
    public void setTotalAmount(String  amount){
       TotalAmount = new BigDecimal(amount).setScale(2, RoundingMode.HALF_UP);
    }
    public void setTableId(int id){
        TableId = id;
    }
    public int getTableId(){
        return TableId;
    }
    public void setCustomerId(int id){
        CustomerId = id;
    }
    public int getCustomerId(){
        return CustomerId;
    }
    public int getMenuId(){
        return MenuId;
    }
    public void setMenuId(int id){
        MenuId = id;
    }
     public int getUnitId(){
        return UnitId;
    }
    public void setUnitId(int id){
        UnitId = id;
    }
      public int getDepartmentId(){
        return DepartmentId;
    }
    public void setDepartmentId(int id){
        DepartmentId = id;
    }
    public void setItemBaseUnit(String  item){
        ItemBaseUnit = item;
    }
    public String getItemBaseUnit(){
        return ItemBaseUnit;
    }
    public void setWaiterId(int id){
        WaiterId = id;
    }
    public int getWaiterId(){
        return WaiterId;
    }
    public void setFocusOnButtonOrder(){
        btnOrder.requestFocus();
    }
     public void setFocusOnButtonEdit(){
        btnOrderEdit.requestFocus();
    }
    public void setFocusOntxtOrderQuantity(){
        txtOrderQuantity.requestFocusInWindow();
    }
    public void setFocusOnAddOrder(){
        btnAdd.requestFocusInWindow();
    }
    public void  setComboTableName(String name){
        comboTableName.setSelectedItem(name);
    }
    public void setComboTableName(String[] name){
        DefaultComboBoxModel TableNameModel = new DefaultComboBoxModel(name);
        comboTableName.setModel(TableNameModel);
    }
    public String getComboTableName(){
        return comboTableName.getSelectedItem().toString();
    }
    public void setComboMenuName(String[] name){
        DefaultComboBoxModel MenuNameModel = new DefaultComboBoxModel(name);
        comboMenuName.setModel(MenuNameModel);
    }
    public void setComboMenuName(String name){
        comboMenuName.setSelectedItem(name);
    }
    public String getComboMenuName(){
         return comboMenuName.getSelectedItem().toString();
    }
    public void setComboWaiterName(String[] name){
        DefaultComboBoxModel WaiterNameModel = new DefaultComboBoxModel(name);
        comboWaiterName.setModel(WaiterNameModel);
    }
    public void setComboWaiterName(String name){
        comboWaiterName.setSelectedItem(name);
    }
    public String setComboWaiterName(){
        return comboWaiterName.getSelectedItem().toString();
    }
    public void setComboCustomerName(String[] name){
        DefaultComboBoxModel CustomerNameModel = new DefaultComboBoxModel(name);
        comboCustomerName.setModel(CustomerNameModel);
    }
    public void setComboCustomerName(String name){
        comboCustomerName.setSelectedItem(name);
    }
    public String getComboCustomerName(){
        return comboCustomerName.getSelectedItem().toString();
    }
    public void setQuantity(Double st){
        txtOrderQuantity.setValue(st);
    }
    public Double getQuantity(){
        return ((Number)txtOrderQuantity.getValue()).doubleValue();
    }
    public void setSearch(String search){
        txtSearch.setText(search);
    }
    public String getSearch(){
         return txtSearch.getText().trim();
    }
    public void setSearchMenu(String src){
        txtSearchMenu.setText(src);
    }
    public String getSearchMenu(){
        return txtSearchMenu.getText().trim();
    }
    public void setcomboDepartmentName(Object[] data){
        DefaultComboBoxModel model = new DefaultComboBoxModel(data);
        comboDepartmentName.setModel(model);
    }
    public void setcomboDepartmentName(String st){
        comboDepartmentName.setSelectedItem(st);
    }
    public String getcomboDepartmentName(){
        return comboDepartmentName.getSelectedItem().toString();
    }
    public JComboBox returnComboDepartmentName(){
        return comboDepartmentName;
    }
     public final void setButtonForEnter(JButton jb){
         jb.registerKeyboardAction(jb.getActionForKeyStroke(
                                      KeyStroke.getKeyStroke(KeyEvent.VK_SPACE, 0, false)),
                                      KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0, false),
                                      JComponent.WHEN_FOCUSED);
 
        jb.registerKeyboardAction(jb.getActionForKeyStroke(
                                      KeyStroke.getKeyStroke(KeyEvent.VK_SPACE, 0, true)),
                                      KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0, true),
                                      JComponent.WHEN_FOCUSED);
        
    }
     
     public void refreshOrderListJTable(DefaultTableModel model){
         tblOrderList.setModel(model);
     }
     public void refreshOrderedListJTable(DefaultTableModel model){
         tblOrderedList.setModel(model);
     }
      public void refreshSearchMenuJTable(DefaultTableModel model){
         tblSearch.setModel(model);
     }

    //return all the txtfield
   

    public JFormattedTextField getTxtOrderQuantity() {
        return txtOrderQuantity;
    }

    public JTextField getTxtSearch() {
        return txtSearch;
    }

    public JTextField getTxtSearchMenu() {
        return txtSearchMenu;
    }

   
    
    
      
     public void addSearchListener(ActionListener ListenForSearch){
         btnSearchOrder.addActionListener(ListenForSearch);
     }
      public void addSearchMenuListener(ActionListener ListenForSearch){
         btnSearchMenu.addActionListener(ListenForSearch);
     }
     public void addAddTableListener(ActionListener ListenForAddTable){
         btnAddTable.addActionListener(ListenForAddTable);
     }
     public void addAddCustomerListener(ActionListener ListenForAddCustomer){
         btnAddCustomer.addActionListener(ListenForAddCustomer);
     }
     public void addAddWaiterListener(ActionListener ListenForAddWaiter){
         btnAddWaiter.addActionListener(ListenForAddWaiter);
     }
    
     public void addAdd(ActionListener ListenForAddOrder){
         btnAdd.addActionListener(ListenForAddOrder);
     }
     public void addTextAdd(ActionListener ListenForAddOrder){
         txtOrderQuantity.addActionListener(ListenForAddOrder);
     }
     public void addDoubleClickListenerForTableSearch(MouseAdapter ListenForDoubleClick){
         tblSearch.addMouseListener(ListenForDoubleClick);
     }
       public void addDoubleClickListenerForOrderedList(MouseAdapter ListenForDoubleClick){
         tblOrderedList.addMouseListener(ListenForDoubleClick);
     }
    /* public void addEditOrder(ActionListener ListenForEditOrder){
         btnEditOrder.addActionListener(ListenForEditOrder);
     }*/
     public void addDelete(ActionListener ListenForDeleteOrder){
         btnDelete.addActionListener(ListenForDeleteOrder);
     }
     /*
      * order function
      */
     public void addAddOrder(ActionListener ListenForOrder){
         btnOrder.addActionListener(ListenForOrder);
     }
     public void addAddOrderAndPrint(ActionListener ListenForOrder){
         btnOrderAndPrint.addActionListener(ListenForOrder);
     }
      public void addEditOrder(ActionListener ListenForOrder){
         btnOrderEdit.addActionListener(ListenForOrder);
     }
      public void addDeleteOrder(ActionListener ListenForDelete){
          btnOrderDelete.addActionListener(ListenForDelete);
      }
     public void addCancelOrder(ActionListener ListenForCancel){
         btnCancelOrder.addActionListener(ListenForCancel);
     }
     public void addComboTableNameListener(ActionListener ListenForTableClick){
         comboTableName.addActionListener(ListenForTableClick);
     }
     public void addComboCustomerNameListener(ActionListener ListenForCustomerClick){
         comboCustomerName.addActionListener(ListenForCustomerClick);
     }
     public void addComboWaiterNameListener(ActionListener ListenForWaiterClick){
         comboWaiterName.addActionListener(ListenForWaiterClick);
     }
     public void addComboMenuNameListener(ActionListener ListenForMenuClick){
         comboMenuName.addActionListener(ListenForMenuClick);
     }
      public void addComboMenuNameItemListener(ItemListener ListenForMenuClick){
         comboMenuName.addItemListener(ListenForMenuClick);
     }
      public void addComboDepartmentListener(ActionListener Listen){
          comboDepartmentName.addActionListener(Listen);
      }
     public void addOrderTableListSelection(ListSelectionListener ListenForList){
         selectionModelOrderTable.addListSelectionListener(ListenForList);
     }
     public void addOrderedTableListSelection(ListSelectionListener ListenForOdered){
         selectionModelOrderedTable.addListSelectionListener(ListenForOdered);
     }
     public void addRefreshOrderedListListener(ActionListener ListenForRefresh){
         btnRefresh.addActionListener(ListenForRefresh);
     }
     //adding delaget for listening fore keyboard shortcut through out the frame
     public void addShortcutForOrder(KeyEventDispatcher Listen){
         kfmanager.addKeyEventDispatcher(Listen);
     }
    
     /*
      * window listenr for close action in add waiter and customenr 
      */
     public void addCloseButtonListener(WindowListener ListenForClose){
         DialogBox.addWindowListener(ListenForClose);
     }
     /*
     adding enter listener in text field
     */
     public void addAbstractActionListener(AbstractAction action){
         //adding action for txtorderquantity
         txtOrderQuantity.getInputMap().put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER,0),"check");
         txtOrderQuantity.getActionMap().put("check", action);
         //adding action for txtsearchmenu
         txtSearchMenu.getInputMap().put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER,0), "ClickSearchMenu");
         txtSearchMenu.getActionMap().put("ClickSearchMenu",action);
         //addin action fo txt search
         txtSearch.getInputMap().put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER,0), "ClickSearch");
         txtSearch.getActionMap().put("ClickSearch", action);
         //adding action for combomenu search box
         comboMenuName.getInputMap().put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER,0), "ComboMenuName");
         comboMenuName.getActionMap().put("ComboMenuName", action);
     }
     public void setAddEditableTrue(){
         btnAdd.setEnabled(true);
     }
     public void setAddEditableFalse(){
         btnAdd.setEnabled(false);
     }
    /* public void setEditOrderEditableFalse(){
         btnEditOrder.setEnabled(false);
     }
     public void setEditOrderEditableTrue(){
         btnEditOrder.setEnabled(true);
     }*/
     public void setDeleteEditableTrue(){
         btnDelete.setEnabled(true);
     }
     public void setDeleteEditableFalse(){
         btnDelete.setEnabled(false);
     }
     public void setAddOrderEditableTrue(){
         btnOrder.setEnabled(true);
     }
     public void setAddOrderEditableFalse(){
         btnOrder.setEnabled(false);
     }
     public void setAddOrderAndPrintEditableFalse(){
         btnOrderAndPrint.setEnabled(false);
     }
     public void setAddOrderAndPrintEditableTrue(){
         btnOrderAndPrint.setEnabled(true);
     }
      public void setEditOrderEditableTrue(){
         btnOrderEdit.setEnabled(true);
     }
     public void setEditOrderEditableFalse(){
         btnOrderEdit.setEnabled(false);
     }
      public void setDeleteOrderEditableTrue(){
         btnOrderDelete.setEnabled(true);
     }
     public void setDeleteOrderEditableFalse(){
         btnOrderDelete.setEnabled(false);
     }
    public DefaultTableModel getTableOrderList(){
        return (DefaultTableModel) tblOrderList.getModel();
    }
    public DefaultTableModel getTableOrderedList(){
        return (DefaultTableModel) tblOrderedList.getModel();
    }
    public DefaultTableModel getSearchTable(){
        return (DefaultTableModel) tblSearch.getModel();
    }
    public void AddSelectInCombo(JComboBox jc){
      jc.insertItemAt("SELECT", 0);
      jc.setSelectedIndex(0);
    }
    public JComboBox returnCustomerComboBox(){
        return comboCustomerName;
    }
    public JComboBox returnWaiterComboBox(){
        return comboWaiterName;
    }
    public JComboBox returnTableComboBox(){
        return comboTableName;
    }
    public JComboBox returnMenuComboBox(){
        return comboMenuName;
    }
    public void clearAddData(){
       
        setMenuId(0);
        setQuantity(0.0);
        setRate("0");
        setItemBaseUnit("");
        setSearchMenu("");
        //setComboTableName(new String());
        
        
    }
    public void  setOrderData(String[] data){
        if(data[0].equals("")){
            comboTableName.setSelectedIndex(0);
        }
        else{
        setComboTableName(data[0]);
        }
       // System.out.println(data[0]);
         if(data[1].equals("")){
            comboCustomerName.setSelectedIndex(0);
        }
         {
        setComboCustomerName(data[1]);
         }
       // System.out.println(data[1]);
          if(data[2].equals("")){
            comboWaiterName.setSelectedIndex(0);
        }
          {
        setComboWaiterName(data[2]);
          }
       // System.out.println(data[2]);
    }
    public  void clearOrderData(){
          comboCustomerName.setSelectedIndex(0);
       comboWaiterName.setSelectedIndex(0);
       if(comboMenuName.getModel().getSize() != 0){
     comboMenuName.setSelectedIndex(0);
       }
     comboTableName.setSelectedIndex(0);
        setOrderId("");
//        setMainOrderId(0);
        setMenuId(0);
        setQuantity(0.0);
       // setRate("0");
        setTableId(0);
        setCustomerId(0);
       setWaiterId(0);
        setItemBaseUnit("");
        setSearchMenu("");
        setSearch("");
       
    }
    public void initComboBox(){
         comboCustomerName.setSelectedIndex(0);
       comboWaiterName.setSelectedIndex(0);
     comboMenuName.setSelectedIndex(0);
     comboTableName.setSelectedIndex(0);
    }
    public void addcomboMenuNameFocus(){
//         comboMenuName.setFocusable(true);
        comboMenuName.requestFocusInWindow();
       
    }

    /*
    return all the button
     */
    public JButton getBtnAdd() {
        return btnAdd;
    }

    public JButton getBtnAddCustomer() {
        return btnAddCustomer;
    }

    public JButton getBtnAddTable() {
        return btnAddTable;
    }

    public JButton getBtnAddWaiter() {
        return btnAddWaiter;
    }

    public JButton getBtnCancelOrder() {
        return btnCancelOrder;
    }

    public JButton getBtnDelete() {
        return btnDelete;
    }
    
    public   JButton getBtnOrder() {
       
        return btnOrder;
    }

    public JButton getBtnOrderAndPrint() {
        return btnOrderAndPrint;
    }

    public JButton getBtnOrderDelete() {
        return btnOrderDelete;
    }

    public JButton getBtnOrderEdit() {
        return btnOrderEdit;
    }

    public JButton getBtnRefresh() {
        return btnRefresh;
    }

    public JButton getBtnSearchMenu() {
        return btnSearchMenu;
    }

    public JButton getBtnSearchOrder() {
        return btnSearchOrder;
    }
   public void ClickAddOrderButton(){
       btnOrder.doClick();
   }
     public void setSVC(Double svc){
            DoubleSVC = svc;
        }
        public Double getSVC(){
            return DoubleSVC;
        }
     public void setVAT(Double Vat){
         DoubleVAT = Vat;
     }
     public Double getVAT(){
         return DoubleVAT;
     }
    
     public Map getOrderParam(){
         Map para = new HashMap<Object, Object>();
         para.put("orderId", Integer.parseInt(lblOrderId.getText().trim()));
         return para;
     }
     public class sAbstractListener extends AbstractAction{

        @Override
        public void actionPerformed(ActionEvent e) {
            System.out.println("wala");
            
        }
         
     }
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderView().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JDialog DialogBox;
    public javax.swing.JDialog SearchDailog;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAddCustomer;
    private javax.swing.JButton btnAddTable;
    private javax.swing.JButton btnAddWaiter;
    private javax.swing.JButton btnCancelOrder;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnOrder;
    private javax.swing.JButton btnOrderAndPrint;
    private javax.swing.JButton btnOrderDelete;
    private javax.swing.JButton btnOrderEdit;
    public javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSearchMenu;
    private javax.swing.JButton btnSearchOrder;
    private javax.swing.JComboBox comboCustomerName;
    private javax.swing.JComboBox comboDepartmentName;
    private javax.swing.JComboBox comboMenuName;
    private javax.swing.JComboBox comboTableName;
    private javax.swing.JComboBox comboWaiterName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblOrderId;
    public javax.swing.JScrollPane scroll;
    public javax.swing.JTable tblOrderList;
    public javax.swing.JTable tblOrderedList;
    public javax.swing.JTable tblSearch;
    public javax.swing.JFormattedTextField txtOrderQuantity;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSearchMenu;
    // End of variables declaration//GEN-END:variables
}
