/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package centerstore.distributorComponent;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.*;
import java.awt.event.ActionListener;
import javax.swing.*;
import javax.swing.event.*;
import javax.swing.table.*;

/**
 *
 * @author MinamRosh
 */
public class DistributerView extends javax.swing.JDialog {

    /**
     * Creates new form DistributerView
     * @param parent
     * @param model, type of dialog box
     */
    public DistributerView(JFrame parent, boolean model) {
        //retrive selection model
        super(parent, model);
        setFont(new Font("Tahoma", Font.PLAIN, 14));
        initComponents();
        disableUpdate();
        
        //set enter and space key actions
        setButtonForEnter(btnAdd);
        setButtonForEnter(btnUpdate);
        setButtonForEnter(btnDelete);
        setButtonForEnter(btnCancel);
        
        setLocationRelativeTo(null);
        
    }
    
    public final void disableUpdate(){
        btnUpdate.setEnabled(false);
    }
    public void disableAdd(){
        btnAdd.setEnabled(false);
    }
    public void enableAdd(){
        btnAdd.setEnabled(true);
    }
    public void enableUpdate(){
        btnUpdate.setEnabled(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDName = new javax.swing.JTextField();
        txtDAdrs = new javax.swing.JTextField();
        txtDPhone = new javax.swing.JTextField();
        txtDEmail = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblDistributor = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Distributer Setup");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Distributer Name * :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Distributer Address * :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Phone * :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("E-mail :");

        txtDName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDNameActionPerformed(evt);
            }
        });
        txtDName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDNameFocusLost(evt);
            }
        });

        txtDAdrs.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtDPhone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtDEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnAdd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAdd.setMnemonic('A');
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnUpdate.setMnemonic('U');
        btnUpdate.setText("Update");

        btnDelete.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDelete.setMnemonic('D');
        btnDelete.setText("Delete");

        btnCancel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCancel.setMnemonic('C');
        btnCancel.setText("Cancel");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(172, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDAdrs)
                            .addComponent(txtDPhone)
                            .addComponent(txtDEmail)
                            .addComponent(txtDName, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(110, 110, 110))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDAdrs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete)
                    .addComponent(btnCancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblDistributor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblDistributor.setToolTipText("Distributer List");
        tblDistributor.setEditingColumn(0);
        tblDistributor.setName("Distributer Info"); // NOI18N
        tblDistributor.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblDistributor.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(tblDistributor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 51, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDNameActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddActionPerformed

    private void txtDNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDNameFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDNameFocusGained

    private void txtDNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDNameFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDNameFocusLost

    public void addListenerToAdd(ActionListener addListener){
        btnAdd.addActionListener(addListener);
    }
    
    public void addListernerToUpdate(ActionListener updateListener){
        btnUpdate.addActionListener(updateListener);
    }
    
    public void addListenerToDelete(ActionListener delListener){
        btnDelete.addActionListener(delListener);
    }
    
    public void addListenerToCancle(ActionListener cancelListener){
        btnCancel.addActionListener(cancelListener);
    }
    
    /*
    public void addFocustListenerToName(FocusListener fAd){
        txtDName.addFocusListener(fAd);
    }
    
    public void addFocusListenerToAdrs(FocusListener fAdrs){
        txtDAdrs.addFocusListener(fAdrs);
    }
    
    public void addFocusListenerToPhone(FocusListener fPhone){
        txtDPhone.addFocusListener(fPhone);
    }
    */
    //for table listener, retriving row only
    public void addListenerToListModel(ListSelectionListener list){
        setSelectionMode();
       listModel.addListSelectionListener(list);
    }
    
    
    public final void setButtonForEnter(JButton jb){
         jb.registerKeyboardAction(jb.getActionForKeyStroke(
                                       KeyStroke.getKeyStroke(KeyEvent.VK_SPACE, 0, false)),
                                      KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0, false),
                                      JComponent.WHEN_FOCUSED);
 
        jb.registerKeyboardAction(jb.getActionForKeyStroke(
                                      KeyStroke.getKeyStroke(KeyEvent.VK_SPACE, 0, true)),
                                      KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0, true),
                                      JComponent.WHEN_FOCUSED);
        
    }
    /*
    public void addKeyListenerToBtn(KeyListener l){
        btnAdd.addKeyListener(l);
        btnUpdate.addKeyListener(l);
        btnDelete.addKeyListener(l);
        btnCancel.addKeyListener(l);
    }
    */
    
  //set foucs listener to text filed
    public void addFocusToField(FocusListener f){
        txtDAdrs.addFocusListener(f);
        txtDName.addFocusListener(f);
        txtDPhone.addFocusListener(f);
        txtDEmail.addFocusListener(f);
    }
    
    //return distro information for adding
    public String[] getDistributorInfo(){
        String[] strDistro = new String[4];
        strDistro[0] = txtDName.getText().trim().toUpperCase();
        strDistro[1] = txtDAdrs.getText().trim().toUpperCase(); 
        strDistro[2] = txtDPhone.getText().trim();
        strDistro[3] = txtDEmail.getText().trim();
        
        return strDistro;
    }
    
    //notification section
    public void setErrName(){
        txtDName.setBorder(BorderFactory.createLineBorder(Color.RED));  
    }
    public void setErrAdrs(){
        txtDAdrs.setBorder(BorderFactory.createLineBorder(Color.RED));  
    }
    public void setErrPhone(){
        txtDPhone.setBorder(BorderFactory.createLineBorder(Color.RED));  
    }
    /*
    public void setErrEmail(){
        txtDEmail.setBorder(BorderFactory.createLineBorder(Color.RED));  
    }
    * */
    public void clearErr(){
        txtDName.setBorder(BorderFactory.createLineBorder(Color.LIGHT_GRAY));
        txtDAdrs.setBorder(BorderFactory.createLineBorder(Color.WHITE));
        txtDPhone.setBorder(BorderFactory.createLineBorder(Color.WHITE));
        txtDEmail.setBorder(BorderFactory.createLineBorder(Color.WHITE));
    }
    
    //clear field
    public void clearTxtField(){
        txtDName.setText("");
        txtDAdrs.setText("");
        txtDPhone.setText("");
        txtDEmail.setText("");
    }
    
    //set table;
    public void setTable(DefaultTableModel tModel){
        distroTable = tModel;
        try{
            tblDistributor.setModel(tModel);
            
        }
        catch(NullPointerException | IllegalArgumentException nulEx){
            
        }
    }
    
    //prepare list  model for listener for table model
    public void setSelectionMode(){
        listModel = tblDistributor.getSelectionModel();
        listModel.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }
    //get listmodel for event handling and retriving diata
    public ListSelectionModel getListModel(){
        return listModel;
    }
    
    //return row element selected in table
    public String[] getRowList(int lead){
        int cols = tblDistributor.getColumnCount();
        //System.out.println(cols);
        //stores each column value of a row
        String rowList[] = new String[cols];
        
        for(int i = 0; i < cols; i++){

           try{
               Object obj = tblDistributor.getValueAt(lead, i);
               rowList[i] = obj.toString();
               //System.out.println(rowList[i].toString());
           }
            catch(NullPointerException | ArrayIndexOutOfBoundsException nulEx){
               //JOptionPane.showMessageDialog(this, nulEx,"Error", JOptionPane.ERROR_MESSAGE);
           }
        }
        //showSelectedRow(rowList);
        return rowList;
        
    }
    
    //shwo selected row list in frame
    public void showSelectedRow(String[] rowList){
        //System.out.println(rowList);
        distroId = Integer.parseInt(rowList[0]);
        txtDName.setText(rowList[1]);
        txtDAdrs.setText(rowList[2]);
        txtDPhone.setText(rowList[3]);
        txtDEmail.setText(rowList[4]);
    }
    
    //delte selected rows in a table
    public void deleteRowTable(int row){
        //tblDistributor.removeAll();
        try{
            distroTable.removeRow(row);
        }
        catch(NullPointerException  ex){
            //System.out.println("executed");
        }
    }
    
    public int getDistroId(){
        return distroId;
    }
    
    public JTable getTable(){
        return tblDistributor;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DistributerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DistributerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DistributerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DistributerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
               // new DistributerView().setVisible(true);
            }
        });
    }
    
    
    private ListSelectionModel listModel;
    private DefaultTableModel distroTable;
    private int distroId;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable tblDistributor;
    private javax.swing.JTextField txtDAdrs;
    private javax.swing.JTextField txtDEmail;
    private javax.swing.JTextField txtDName;
    private javax.swing.JTextField txtDPhone;
    // End of variables declaration//GEN-END:variables
}
