/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package centerstore.itemEnteryComponent;

//import java.awt.Frame;
import javax.swing.*;
import java.awt.event.*;
import java.awt.event.ActionListener;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.table.*;
import javax.swing.event.*;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author MinamRosh
 */
public class ItemEnteryView extends javax.swing.JDialog {

    /**
     * Creates new form ItemEnteryView
     * @param parent
     * @param model
     */
    public ItemEnteryView(JFrame parent, boolean model) {
        super(parent, model);
        
        initComponents();
        //this.getContentPane().setFont(new Font("Tahoma",Font.PLAIN,14));
        comboItemBUnit.setSelectedItem(1);
        //setVisible(true);
        //setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        setButtonForEnter(btnAdd);
        setButtonForEnter(btnUpdate);
        setButtonForEnter(btnDelete);
        setButtonForEnter(btnCancel);
        setButtonForEnter(btnDistro);
        setButtonForEnter(btnSearch);
        //doesn't allow user to select past date for expiry date of a product.
        txtExDate.setMinSelectableDate(new Date());
        
        disableUpdate();
       
        setLocationRelativeTo(null);
        //disableField();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        frameScroller = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        lblIName = new javax.swing.JLabel();
        txtItemName = new javax.swing.JTextField();
        lblCategory = new javax.swing.JLabel();
        comboItemCategory = new javax.swing.JComboBox();
        lblBaseUnit = new javax.swing.JLabel();
        comboItemBUnit = new javax.swing.JComboBox();
        lblQty = new javax.swing.JLabel();
        txtQty = new javax.swing.JTextField();
        lblExDate = new javax.swing.JLabel();
        lblBRate = new javax.swing.JLabel();
        txtBRate = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnSearch = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        itemTable = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        btnDelete = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtTheresHold = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        comboDistributor = new javax.swing.JComboBox();
        btnDistro = new javax.swing.JButton();
        txtExDate = new com.toedter.calendar.JDateChooser();

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("New Item Entery Window");

        frameScroller.setAutoscrolls(true);

        lblIName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblIName.setText("Item Name :*");

        txtItemName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblCategory.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCategory.setText("Category :*");

        comboItemCategory.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comboItemCategory.setModel(new javax.swing.DefaultComboBoxModel());

        lblBaseUnit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblBaseUnit.setText("Base Unit :*");

        comboItemBUnit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comboItemBUnit.setModel(new javax.swing.DefaultComboBoxModel());

        lblQty.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblQty.setText("Quantity :");

        txtQty.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtQty.setText("0");
        txtQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQtyActionPerformed(evt);
            }
        });

        lblExDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblExDate.setText("Expire Date :*");

        lblBRate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblBRate.setText("Buy Rate :");

        txtBRate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtBRate.setText("0.00");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Search Bar"));

        btnSearch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSearch.setMnemonic('S');
        btnSearch.setText("Search");

        txtSearch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Search Item");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel9)
                .addGap(31, 31, 31)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        itemTable.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        itemTable.getTableHeader().setReorderingAllowed(false);
        itemTable.setFillsViewportHeight(true);
        itemTable.setRowHeight(20);
        jScrollPane4.setViewportView(itemTable);

        btnDelete.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDelete.setMnemonic('D');
        btnDelete.setText("Delete");

        btnAdd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAdd.setMnemonic('A');
        btnAdd.setText("Add");

        btnCancel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCancel.setMnemonic('C');
        btnCancel.setText("Cancel");

        btnUpdate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnUpdate.setMnemonic('E');
        btnUpdate.setText("Edit");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Threshold :*");

        txtTheresHold.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTheresHold.setText("0");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Distributor :*");

        comboDistributor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comboDistributor.setModel(new javax.swing.DefaultComboBoxModel());

        btnDistro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDistro.setText("Add Distributor");
        btnDistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDistroActionPerformed(evt);
            }
        });

        txtExDate.setDateFormatString("yyyy-M-dd");
        txtExDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(158, 158, 158)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblIName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblCategory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(53, 53, 53)
                                        .addComponent(txtItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblBRate, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(lblExDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(51, 51, 51))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(lblBaseUnit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(44, 44, 44)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(comboItemBUnit, 0, 163, Short.MAX_VALUE)
                                            .addComponent(comboItemCategory, 0, 163, Short.MAX_VALUE)
                                            .addComponent(txtBRate, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                            .addComponent(txtTheresHold)
                                            .addComponent(comboDistributor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtExDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblQty)
                                        .addGap(25, 25, 25)
                                        .addComponent(txtQty, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnDistro)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(140, 140, 140)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(117, 117, 117)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 167, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboItemCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBaseUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboItemBUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQty)
                    .addComponent(txtQty, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBRate, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBRate, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblExDate, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtExDate, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTheresHold, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboDistributor, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDistro, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                .addContainerGap())
        );

        frameScroller.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(frameScroller)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(frameScroller)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQtyActionPerformed

    private void btnDistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDistroActionPerformed

    
    /* sub unit section */
   
    /* end of sub unit section */
    
    /*main listener section */
    public void addListenerToAdd(ActionListener lAd){
        btnAdd.addActionListener(lAd);
    }
    public void addListenerToUpdate(ActionListener lUp){
        btnUpdate.addActionListener(lUp);
    }
    public void addListenerToDelete(ActionListener lDel){
        btnDelete.addActionListener(lDel);
    }
    public void addListenerToCancel(ActionListener lCn){
        btnCancel.addActionListener(lCn);
    }
    public void addListenerToDistro(ActionListener lDi){
        btnDistro.addActionListener(lDi);
    }
    public void addListenerToSearch(ActionListener lSr){
        btnSearch.addActionListener(lSr);
    }
    
     public void addFocusToField(FocusListener f){
        txtBRate.addFocusListener(f);
        txtExDate.addFocusListener(f);
        txtItemName.addFocusListener(f);
        txtQty.addFocusListener(f);
        txtSearch.addFocusListener(f);
        txtTheresHold.addFocusListener(f);
    }
     
     /*listener used to listen each key stroke in search box and forward it
     */
     public void addDocumentListenerToSearch(DocumentListener d){
         txtSearch.getDocument().addDocumentListener(d);
     }
     
     /**
      * add action lister to text field which initiate the search func
      * @param a
      */
     public void addAListenerToSText(ActionListener a){
         txtSearch.addActionListener(a);
     }
     
     /**
      * display table with new data
      * @param tModel 
      */
     public void refreshItemTable(DefaultTableModel tModel){
         itemTable.setModel(tModel);
     }
   //key listener;
    /*
    public void addKeyListenerToBtn(KeyListener l){
        btnAdd.addKeyListener(l);
        btnUpdate.addKeyListener(l);
        btnDelete.addKeyListener(l);
        btnCancel.addKeyListener(l);
        
        btnSearch.addKeyListener(l);
    }
    //key listener to add distributor button
    public void addKeyListenerToDistro(KeyListener l){
        btnDistro.addKeyListener(l);
    }
    */
    public final void setButtonForEnter(JButton jb){
         jb.registerKeyboardAction(jb.getActionForKeyStroke(
                                       KeyStroke.getKeyStroke(KeyEvent.VK_SPACE, 0, false)),
                                      KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0, false),
                                      JComponent.WHEN_FOCUSED);
 
        jb.registerKeyboardAction(jb.getActionForKeyStroke(
                                      KeyStroke.getKeyStroke(KeyEvent.VK_SPACE, 0, true)),
                                      KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0, true),
                                      JComponent.WHEN_FOCUSED);
        
    }
    /*public String getItemName(){
        return txtItemName.getText().trim();
    }
    public int getQty(){
        return Integer.parseInt(txtQty.getText().trim());
    }
    public int getBuyRate(){
        return Integer.parseInt(txtBRate.getText().trim());
    }
   
    public int getExDate(){
        return 0;
    }
    public int getLimit(){
        return Integer.parseInt(txtTheresHold.getText().trim());
    }
   */
    public String getSearchItem(){
        return txtSearch.getText().trim();
    }
    
   
    
    public String[] txtItem(){
        SimpleDateFormat n = new SimpleDateFormat("yyyy-MM-dd");
        String exDate = n.format(txtExDate.getJCalendar().getDate()).toString();
        String[] data = new String[]{txtItemName.getText().trim(), txtQty.getText().trim(), txtBRate.getText().trim(),
           exDate, txtTheresHold.getText().trim()};
        //System.out.println(n.format(txtExDate.getJCalendar().getDate()).toString());
        
        return data;
    }
    //set distributer list;
    public void setComboDistroList(String[] distroList){
        String[] distro = null;
        if(distroList.length <= 0){
            distro = new String[1];
            distro[0] = "No Distributor List";
        }
        else{
            distro = new String[distroList.length+1];
            distro[0] = "Select Distributor";
            for(int i = 0; i < distroList.length; i++){
                distro[i+1] = distroList[i];
        }
        }
        distroModel = new DefaultComboBoxModel(distro);
        comboDistributor.setModel(distroModel);
    }
    public String getSelectedDistro(){
        return comboDistributor.getSelectedItem().toString();
    }
    
    //set category list
    public void setComboCategoryList(String[] categoryList){
        String[] category = null;
        if(categoryList.length <= 0){
            category = new String[1];
            category[0] = "No Category List";
        }
        else{
            category = new String[categoryList.length+1];
            category[0] = "Select Category";
            for(int i = 0; i < categoryList.length; i++){
                category[i+1] = categoryList[i];
            }
        }
        categoryModel = new DefaultComboBoxModel(category);
        comboItemCategory.setModel(categoryModel);
    }
    //get slected category
    public String getSelectedCategory(){
        return comboItemCategory.getSelectedItem().toString();
    }
    
    //set base unit list
    public void setComboUnitList(String[] unitList){
        String[] unit = null;
        if(unitList.length <= 0){
            unit = new String[1];
            unit[0] = "No Unit List";
        }
        else{
            unit = new String[unitList.length+1];
            unit[0] = "Select Unit";
            for(int i = 0; i < unitList.length; i++){
                unit[i+1] = unitList[i];
            }
        }
        baseUModel = new DefaultComboBoxModel(unit);
        comboItemBUnit.setModel(baseUModel);
    }
    //get selected base unit
    public String getSelectedUnit(){
        return comboItemBUnit.getSelectedItem().toString();
    }
    
    public void clearComboList(){
        comboItemBUnit.setSelectedIndex(0);
        comboItemCategory.setSelectedIndex(0);
        comboDistributor.setSelectedIndex(0);
    }
    
    //set combo sub unit
    
    //clear all filed
    public void clearAllField(){
        txtItemName.setText("");
        txtBRate.setText("0.00");
        txtQty.setText("0");
        txtSearch.setText("");
        txtTheresHold.setText("0");
        txtExDate.setDate(null);
        
    }
    
    public void setTableModel(DefaultTableModel tm){
        try{
            tblItemModel = tm;
            itemTable.setModel(tblItemModel);
        }
        catch(NullPointerException ex){
            displayErr("ItemEnteryView.setTableModel(): " +ex.getLocalizedMessage());
        }
        
    }
    /* handling table*/
    public void addListenerToListModel(ListSelectionListener l){
        setSelectionModeTable();
        listItemModel.addListSelectionListener(l);
    }
    //set selection model for event handling
    public void setSelectionModeTable(){
        listItemModel = itemTable.getSelectionModel(); //retrive selection model of table
        listItemModel.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);//sets selection model
    }
    //return list model for retrivein data
    public ListSelectionModel getListModel(){
        return listItemModel;
    }
    //return table
    public JTable getTable(){
        return itemTable;
    }
    public void displayErr(String msg){
        JOptionPane.showMessageDialog(this, msg, null, JOptionPane.ERROR_MESSAGE);
    }
    
    public void showSelectedRowList(String[] list){
        
        itemId = list[0];
        
        txtItemName.setText(list[1]);
        comboItemCategory.setSelectedItem(list[2]);
        comboItemBUnit.setSelectedItem(list[3]);
        txtQty.setText(list[4]);
        txtBRate.setText(list[5]);
        txtTheresHold.setText(list[6]);
        comboDistributor.setSelectedItem(list[7]);
        try {
            txtExDate.setDate(new SimpleDateFormat("yyyy-MM-dd").parse(list[8]));
            //txtExDate.setDate( new Date);
        } catch (ParseException ex) {
            Logger.getLogger(ItemEnteryView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void deleteRowTable(int row){
        //tblDistributor.removeAll();
        try{
            tblItemModel.removeRow(row);
        }
        catch(NullPointerException  ex){
            
        }
    }
    
    public String getItemId(){
        return itemId;
    }
    
     public void disableUpdate(){
        btnUpdate.setEnabled(false);
    }
    public void disableAdd(){
        btnAdd.setEnabled(false);
    }
    public void enableAdd(){
        btnAdd.setEnabled(true);
    }
    public void enableUpdate(){
        btnUpdate.setEnabled(true);
    }
    
    /**
     * used to pass search button to the controller to attach action event
     * @return srchBtn, JButton
     */
    public JButton getSearchBtn(){
        return btnSearch;
    }
    
    /**
     * highlight the selected row on the table and make it on top
     * @param r, int row no;
     * @param c int col no.
     */
    public void setSItemTable(int r, int c){
        itemTable.scrollRectToVisible(itemTable.getCellRect(r, c, true));
        itemTable.setRowSelectionInterval(r, r);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel *
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ItemEnteryView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ItemEnteryView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ItemEnteryView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ItemEnteryView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                //new ItemEnteryView().setVisible(true);
            }
        });
    }
   /* 
    public void setDateFromat(){
        DateFormat date = new SimpleDateFormat("mm/yy/yyyy");
        txtExDate.setValue(date);
    }
    */
    public void disableField(){
        comboDistributor.setEnabled(false);
        comboItemBUnit.setEnabled(false);
        txtQty.setEnabled(false);
        txtBRate.setEnabled(false);
        txtExDate.setEnabled(false);
        txtTheresHold.setEnabled(false);
        btnDistro.setEnabled(false);
    }
    
    public void enableField(){
        comboDistributor.setEnabled(true);
        comboItemBUnit.setEnabled(true);
        txtQty.setEnabled(true);
        txtBRate.setEnabled(true);
        txtExDate.setEnabled(true);
        txtTheresHold.setEnabled(true);
        btnDistro.setEnabled(true);
    }
    
    private String itemId = "0";
    private ListSelectionModel listItemModel;
    private DefaultTableModel tblItemModel;
    private DefaultComboBoxModel subUModel;
    private DefaultComboBoxModel baseUModel;
    private DefaultComboBoxModel categoryModel;
    private DefaultComboBoxModel distroModel;
    private String[] itemEnteryInfo;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDistro;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox comboDistributor;
    private javax.swing.JComboBox comboItemBUnit;
    private javax.swing.JComboBox comboItemCategory;
    private javax.swing.JScrollPane frameScroller;
    private javax.swing.JTable itemTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable3;
    private javax.swing.JLabel lblBRate;
    private javax.swing.JLabel lblBaseUnit;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JLabel lblExDate;
    private javax.swing.JLabel lblIName;
    private javax.swing.JLabel lblQty;
    private javax.swing.JTextField txtBRate;
    private com.toedter.calendar.JDateChooser txtExDate;
    private javax.swing.JTextField txtItemName;
    private javax.swing.JTextField txtQty;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtTheresHold;
    // End of variables declaration//GEN-END:variables
}
